// src/lib/drill-data.ts
// Enriched drill data — used by DrillCard component and drills page

export type PositionKey = "striker" | "midfielder" | "defender" | "goalkeeper" | "winger";
export type EquipmentTier = "zero" | "basic" | "gym";
export type DrillCategory = "Technical" | "Physical" | "Tactical";
export type AgeGroup = "u13" | "u16" | "u19" | "senior";

export interface AgeVariant {
  instructions: string[];
  coaching_notes?: string;
}

export interface DrillData {
  id: string;
  name: string;
  duration: string;
  description: string;
  category: DrillCategory;
  football_benefit: string;
  instructions: string[];
  success_feels_like: string;
  gemini_scores: string[];
  equipment_tier: EquipmentTier;
  position_tags: string[];
  muscles_targeted: string[];
  difficulty_level: 1 | 2 | 3;
  is_premium: boolean;
  // Context fields
  when_to_use?: string;   // The game situation or phase of play where this skill is needed
  where_on_pitch?: string; // The pitch zone or positional context where this drill applies
  // Optional enhancement fields
  age_variants?: Partial<Record<AgeGroup, AgeVariant>>;
  gender_notes?: string;
  i18n?: {
    sn?: { name?: string; instructions?: string[] };
    nd?: { name?: string; instructions?: string[] };
  };
}

export interface PositionTrack {
  title: string;
  focus: string;
  drills: DrillData[];
}

export const FOOTBALL_POSITION_DRILLS: Record<PositionKey, PositionTrack> = {
  striker: {
    title: "Striker & Attacking Forward Track",
    focus: "Attacking intent, positive first-touch control, creative blind turns, and clinical box execution.",
    drills: [
      {
        id: "eng_st_01",
        name: "Lions' Den Central Turning",
        duration: "15 mins",
        category: "Technical",
        description: "Receive a firm vertical entry pass inside a tight 8x8-yard square under physical contact. Protect the ball with your body, turn sharply on the half-turn, and play forward to a teammate.",
        football_benefit: "A striker who can hold up play under physical pressure keeps the whole team's attack alive. This drill builds the confidence and technique to receive with defenders on your back — the foundation of all link-up play in tight spaces.",
        instructions: [
          "Set up an 8×8 yard square using 4 cones",
          "Ask a partner to apply body-contact pressure from directly behind you inside the square",
          "Receive a firm ground pass from a third player outside the square",
          "Use your arms and body weight to shield the ball from your marker",
          "Turn sharply on the half-turn — Cruyff, drag-back, or outside hook",
          "Play the ball forward out of the square to a target player",
          "Reset and repeat — aim for 0 ball losses across 6 consecutive turns",
        ],
        success_feels_like: "The ball stays glued to your feet despite the pressure. Your body is between defender and ball throughout the entire turn. One fluid motion — receive, shield, spin, release — and the ball is forward before the defender can react.",
        gemini_scores: ["Body Shield Position", "Turn Sharpness", "Balance Under Contact", "Pass Accuracy After Turn"],
        equipment_tier: "basic",
        position_tags: ["Striker", "Number 10", "Winger"],
        muscles_targeted: ["Core", "Glutes", "Hip flexors", "Ankle stabilisers"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use when your team is building through a striker dropping deep to link play — especially when the opposition are pressing high and your midfield needs an outlet. Also crucial whenever you receive with a defender already on your back.",
        where_on_pitch: "Between the opposition's midfield and defensive lines — the tight central corridor roughly 10–25 yards from goal. Any congested space where you must receive and turn under contact.",
        age_variants: {
          u13: {
            instructions: [
              "Set up a 6×6 yard square with 4 cones",
              "A partner stands beside you — shoulder contact only, no pushing",
              "Receive a soft pass from a third player outside the square",
              "Use your body to stay between the ball and your partner",
              "Turn slowly using a drag-back — take your time to get it right",
              "Play the ball out of the square to a target player",
            ],
            coaching_notes: "Focus on body shape, not speed. Reward correct technique even if slow.",
          },
          u16: {
            instructions: [
              "Set up a 7×7 yard square using 4 cones",
              "Partner applies shoulder-to-shoulder pressure from behind",
              "Receive a firm pass from outside the square",
              "Use your forearm (not elbow) to create space and shield",
              "Turn using a Cruyff or drag-back at moderate pace",
              "Play forward to a target — aim for 5 clean turns in a row",
            ],
            coaching_notes: "Introduce 'pre-turning' — deciding your direction before the ball arrives.",
          },
        },
        i18n: {
          sn: {
            name: "Kupotera Mumuzinda — Nzira dzeKupona",
            instructions: [
              "Isa mahombekombe mana kuti ugadzire nzvimbo yevasere 8×8",
              "Umwe wenzako anobva shure kuzokumanikidza nemuviri",
              "Gamuchira pasi rinouya kubva kunze kwenzvimbo",
              "Shandisa muviri wako kurinda bhora kubva kumukwikwidzi",
              "Tendeuka nekukurumidza — Cruyff, drag-back, kana hook yeninja",
              "Tuma bhora mberi kunze kwenzvimbo kumuteyi",
            ],
          },
        },
      },
      {
        id: "eng_st_02",
        name: "Tri-Third Elimination End Zones",
        duration: "20 mins",
        category: "Tactical",
        description: "Combine out of the defensive third to play an incisive line-breaking pass past the midfield layer. Time your forward run into the shaded end zone to collect and finish without running offside.",
        football_benefit: "Strikers lose their markers with movement, not just pace. This drill trains the timing and angle of your forward runs — arriving in dangerous space at exactly the right moment rather than sprinting and being tracked.",
        instructions: [
          "Mark a 40×25 pitch divided into three equal thirds with cones",
          "Start positioned in the middle third with a defender tracking you",
          "Two midfielders build play through the defensive third with short passes",
          "Watch the ball and the space behind the last defender simultaneously",
          "Time your diagonal run into the shaded end zone as the pass breaks through",
          "Collect the ball on the half-turn already facing goal",
          "Finish with your first or second touch — aim for near or far post in turn",
          "Rotate positions after every 3 runs",
        ],
        success_feels_like: "You arrive in the end zone just as the ball does — not early (defender tracks back) and not late (space has closed). Your body is already half-turned toward goal before the ball reaches your feet.",
        gemini_scores: ["Run Timing", "Body Shape on Arrival", "First Touch Direction", "Finish Technique"],
        equipment_tier: "basic",
        position_tags: ["Striker", "Winger"],
        muscles_targeted: ["Quadriceps", "Hip flexors", "Glutes", "Calves"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use when your team regains possession deep and wants to launch a quick attack with a line-breaking pass behind the last defender. Train this during any shape that uses a striker as the furthest player up the pitch.",
        where_on_pitch: "The space behind the opposition's last defensive line — roughly from the halfway mark through to the final third. The run starts in the central or inside-left/right channels and arrives in the shaded zone level with or beyond the last defender.",
        age_variants: {
          u13: {
            instructions: [
              "Mark a 25×18 yard area divided into two halves (no thirds) with cones",
              "One defender tracks the striker from the centre line",
              "A coach or parent plays simple passes to feet",
              "Striker collects and dribbles to the end zone — no finishing required yet",
              "Award a point for reaching the end zone in control",
            ],
            coaching_notes: "Remove the finish for U13 — spatial awareness and run timing are the priority at this age.",
          },
          u16: {
            instructions: [
              "Mark a 35×22 yard pitch divided into three thirds",
              "Start in the middle third with one defender tracking you",
              "Two players build play short in the defensive third",
              "Time your diagonal run into the shaded end zone as the pass breaks through",
              "Control on the half-turn and finish — or square to a teammate",
              "Rotate every 4 runs",
            ],
            coaching_notes: "Emphasise timing over pace — arrive just before the ball does, not early.",
          },
        },
      },
      {
        id: "eng_st_03",
        name: "Three-Goal Endline Finale",
        duration: "15 mins",
        category: "Tactical",
        description: "Small-sided competitive match attacking a baseline with one large central goal and two corner mini-goals. Any regular goal is 1 point; a first-time finish is worth 2 points.",
        football_benefit: "Finishing is a decision as much as a skill. The three-goal format forces you to read which target is open in a split second and reward first-time finishes — the highest-value skill in a striker's toolkit.",
        instructions: [
          "Set up one large central goal and two small corner mini-goals on the baseline",
          "Play 3v3 or 4v4 in a 30×20 yard area attacking the baseline",
          "Regular goals count 1 point; any first-time finish counts 2 points",
          "Defending team can score on a single goal at the opposite end",
          "Rotate goalkeepers every 3 minutes if available",
          "Before receiving, scan all three targets so you already know the decision",
          "Play for 15 minutes — highest-scoring team wins",
        ],
        success_feels_like: "You scan for all three goals before the ball arrives. The decision is made before the touch. One contact, the right target, maximum power transferred cleanly — and you already know which goal was open.",
        gemini_scores: ["Pre-Touch Scan", "Decision Speed", "Shooting Technique", "Body Shape at Contact"],
        equipment_tier: "basic",
        position_tags: ["Striker", "Winger", "Midfielder"],
        muscles_targeted: ["Quadriceps", "Hip flexors", "Core", "Ankle stabilisers"],
        difficulty_level: 1,
        is_premium: false,
        when_to_use: "Use as the finishing component of any session — when players need to practice making fast decisions under a real competitive constraint. Replaces flat shooting practice with a format that mirrors actual match decision-making.",
        where_on_pitch: "Inside and around the penalty box — anywhere a shooting opportunity arises in the final third. The three-goal layout recreates the split-second read of which target is available that strikers face on every chance.",
      },
      {
        id: "eng_st_04",
        name: "Double Trouble Combination",
        duration: "15 mins",
        category: "Tactical",
        description: "Attack a keeper and defender in pairs on a 35x25-yard pitch. Move and combine to open up space and score. If the defender wins it, recover to help your unit.",
        football_benefit: "Strikers rarely attack alone. Learning to combine — using wall passes, overlaps, and one-twos — is what separates a dangerous forward line from two isolated players waiting for the ball.",
        instructions: [
          "Set up a 35×25 yard pitch with a goal and goalkeeper at one end",
          "Two strikers start from the halfway line against one keeper and one defender",
          "Each combination must include at least one give-and-go before shooting",
          "Options: wall pass, diagonal run, dummy then return, overlap",
          "If the defender wins possession they break to a target at halfway — sprint to recover immediately",
          "Shoot when you have clear space — don't wait for a perfect moment",
          "Rotate the defender every 5 minutes",
        ],
        success_feels_like: "The combination feels like a conversation you've had a hundred times. You know where your partner is going before they move. The defender is left marking empty space while you finish at goal.",
        gemini_scores: ["Combination Timing", "Off-Ball Movement", "First Touch Under Pressure", "Finish Accuracy"],
        equipment_tier: "basic",
        position_tags: ["Striker", "Winger"],
        muscles_targeted: ["Quadriceps", "Hip flexors", "Core", "Calves"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use when working on striker combinations during counter-attack drills or when developing a two-forward partnership. Perfect for sessions focused on attacking transition — moments just after winning the ball in midfield.",
        where_on_pitch: "The central corridor from the edge of the centre circle to the penalty spot — the attacking half of the pitch where two forwards can operate in tandem before defenders have time to recover.",
      },
      {
        id: "eng_st_05",
        name: "The Great Escape Funnel",
        duration: "20 mins",
        category: "Technical",
        description: "Start inside a cone funnel before breaking out into a 35x35-yard area against two central guards. Use feints and body movement to disguise your intentions and escape through perimeter gates.",
        football_benefit: "Strikers must be masters of disguise. Using feints, body shifts, and changes of direction to lose markers is an art — this drill teaches you to use your whole body to deceive and create space from nothing.",
        instructions: [
          "Place 4 cones to create a funnel: 6 yards wide at entry, 12 yards wide at exit",
          "Two guards stand at the funnel entrance — they stay within arm's length of each cone side",
          "Start inside the funnel and receive a pass from a server behind the guards",
          "Use a feint, step-over, or shoulder drop to commit one guard to a direction",
          "Accelerate past both guards through the wide end of the funnel",
          "Shoot at a goal positioned 15 yards past the funnel exit",
          "Score: 1 point for each clean escape, 2 points for a subsequent finish",
          "5 attempts per round — rotate guards every 2 rounds",
        ],
        success_feels_like: "The guard commits to one side based on your body movement — and you're already past them going the other way. Your feint shifted their weight. Now there is open space and you are accelerating through it.",
        gemini_scores: ["Feint Technique", "Change of Direction", "Acceleration Out of Feint", "Body Deception Quality"],
        equipment_tier: "basic",
        position_tags: ["Striker", "Winger", "Midfielder"],
        muscles_targeted: ["Quadriceps", "Hip flexors", "Core", "Glutes"],
        difficulty_level: 3,
        is_premium: true,
        when_to_use: "Use when a striker needs to create their own chance in tight spaces without a wall pass or overlap available — the solo escape. Key in sessions where the opposition press aggressively and isolate the forward.",
        where_on_pitch: "The half-space just outside the penalty area — the zone between the centre circle and the 18-yard box. Anywhere you face two defenders and must use deception alone to get through.",
      },
    ],
  },

  midfielder: {
    title: "Central Midfield & Pivot Track",
    focus: "Pre-receipt shoulder scanning, body shape openness, cover shadows drop, and tactical point switches.",
    drills: [
      {
        id: "cat_md_01",
        name: "Barcelona 3-2-1 Build Up Choices",
        duration: "15 mins",
        category: "Tactical",
        description: "7v7 positional small-sided game. Receive deep build-up passes from the center-back, scan before receiving, use your back foot to open your body shape, and decide whether to combine via a wall-pass or switch play wide.",
        football_benefit: "The best midfielders already know their next pass before the ball arrives. This drill trains the scanning habit and open body shape that turns a simple receive into an instant attacking threat — the hallmark of elite central midfielders.",
        instructions: [
          "Set up a 7v7 on a half-pitch positional game with fixed starting positions",
          "Midfielder's trigger: as the centre-back receives, check your shoulder immediately",
          "Open your body to face forward as you receive — use your back foot to point your hips outward",
          "Read the available options: wall-pass through the lines, wide switch, or recycle",
          "Play forward whenever you safely can — do not recycle as a default",
          "If pressed, protect and recycle — do not force a bad pass",
          "Coach calls 'SCAN' at random moments — freeze and state what you saw",
          "Play 15 minutes total with regular role rotations",
        ],
        success_feels_like: "When the ball is played to you, you already know where your next two passes are. Your body opens naturally and the ball never stops — it just changes direction through you, instantly and with purpose.",
        gemini_scores: ["Shoulder Scan Frequency", "Body Shape Openness", "Decision Speed", "Pass Weight and Direction"],
        equipment_tier: "basic",
        position_tags: ["Midfielder", "Defensive Midfielder"],
        muscles_targeted: ["Core", "Hip flexors", "Neck mobility", "Ankle stabilisers"],
        difficulty_level: 3,
        is_premium: true,
        when_to_use: "Use in build-up play sessions — whenever your team starts from the back and needs midfielders to offer a reliable link between the defensive and attacking lines. Specifically in moments when the goalkeeper or centre-back has the ball.",
        where_on_pitch: "The central midfield area — roughly between your own penalty area and the halfway line. The midfielder must constantly find pockets between the opposition's midfield and defensive lines, scanning across a 30-yard band.",
      },
      {
        id: "eng_md_02",
        name: "Around the Clock Passing Ring",
        duration: "12 mins",
        category: "Technical",
        description: "Position symmetrically around a 20-yard diameter circle. Execute rapid one-touch and two-touch passing patterns through and across the clock structure to break blocks while central defenders chase interceptions.",
        football_benefit: "Clean, quick passing under pressure is the core skill of all great midfielders. The ring structure forces accurate play in all directions with no hiding spot — every mis-touch is visible and every clean pass reinforces the habit.",
        instructions: [
          "Place 8 cones in a circle 20 yards in diameter — like a clock face at each hour",
          "8 players stand on cones; 2 defenders roam freely inside the circle",
          "Begin with two-touch passing — progress to one-touch after 3 minutes",
          "If a defender intercepts, the player who lost the ball swaps in as a defender",
          "Progressions: call a number across the clock before receiving, then play to that position",
          "Play 4 minutes straight — then rotate two new defenders in",
          "Target: zero intercepted passes per 4-minute round",
        ],
        success_feels_like: "The ball never really stops — it deflects from foot to foot like a machine. You are always already pointing toward the next option before the ball reaches you. Defenders look stuck because the ball moves faster than they think.",
        gemini_scores: ["Pass Accuracy", "First Touch Quality", "Body Orientation", "Speed of Play"],
        equipment_tier: "zero",
        position_tags: ["Midfielder", "Defender", "Striker"],
        muscles_targeted: ["Core", "Hip flexors", "Ankle stabilisers"],
        difficulty_level: 1,
        is_premium: false,
        when_to_use: "Use as a warm-up or technical sharpener at the start of any possession-based session. Also ideal mid-session when players need to refresh passing habits before a more complex tactical exercise.",
        where_on_pitch: "The central third — anywhere tight passing triangles and circles naturally form in play. The rondo circle simulates the 5-10 yard passing lanes that appear constantly when a team holds possession in the middle of the pitch.",
      },
      {
        id: "eng_md_03",
        name: "Connect Four Corner Squares",
        duration: "20 mins",
        category: "Tactical",
        description: "A 35x20-yard directional transition game. Midfielders use quick horizontal circulation to pull the defensive block out of alignment, then launch a vertical through-ball into any of the 4 shaded corner target boxes.",
        football_benefit: "Midfielders who can switch play quickly stretch defences horizontally. This drill builds the vision and technique to circulate the ball under pressure before launching the decisive vertical pass that unlocks a defence.",
        instructions: [
          "Set up a 35×20 pitch with 4 shaded corner target boxes (5×5 yards) at each corner",
          "Play 5v5 or 6v6 in the central area — defenders cannot enter corner boxes",
          "Score a point by passing into a corner box with a teammate receiving inside it",
          "After scoring a corner point, build from the opposite end",
          "Progression: require two different corner targets before counting a goal",
          "Defenders must track the ball — draw them one way, then switch",
          "Play 20 minutes — the team with most corner points wins",
        ],
        success_feels_like: "You draw defenders toward you with short passes, then switch the ball before they can shift. The target box is empty for exactly two seconds — and the pass arrives flat and fast into that space.",
        gemini_scores: ["Decision Speed", "Pass Accuracy Under Pressure", "Body Shape", "Switch of Play Weight"],
        equipment_tier: "basic",
        position_tags: ["Midfielder", "Defensive Midfielder", "Winger"],
        muscles_targeted: ["Core", "Hip flexors", "Ankle stabilisers"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use when training against a deep-block defence that packs the central areas. Develops the horizontal circulation and patience needed to stretch a compact defence before playing the decisive vertical pass.",
        where_on_pitch: "The central and wide midfield zone — from your own half through to the edge of the opposition's penalty area. The switches of play travel across the full width of the pitch, so the drill applies to every zone between the two touchlines.",
      },
      {
        id: "eng_md_04",
        name: "Table Football Tri-Thirds Match",
        duration: "25 mins",
        category: "Tactical",
        description: "Play a match inside a field split into thirds where outfielders are entirely locked into their areas to emphasize vertical lines. Work the ball dynamically through the thirds to feed your striker.",
        football_benefit: "Playing locked into a third teaches midfielders their role in the team's vertical structure. You cannot hide or drift — you must constantly make yourself available and play every ball with immediate purpose.",
        instructions: [
          "Divide a full pitch into three equal thirds with cone lines",
          "Each outfield player is locked strictly inside their designated third — no crossing the lines",
          "Only the ball can travel between thirds via pass or lofted ball",
          "Midfielders work in the middle third: receive from defence, play forward to attack",
          "Coach blows whistle if anyone crosses into another third — instant turnover of possession",
          "Midfielders must use the full width of their third to find forward options",
          "Play 25 minutes with normal scoring — switch roles at half time",
        ],
        success_feels_like: "You become a relay station between two worlds. Every ball that comes to you must go forward better than it arrived — with more pace, in a better direction, at a teammate who has more time than you did.",
        gemini_scores: ["Positioning in Middle Third", "Body Shape on Receive", "Pass into Final Third", "Decision Speed"],
        equipment_tier: "basic",
        position_tags: ["Midfielder", "Defensive Midfielder"],
        muscles_targeted: ["Core", "Ankle stabilisers", "Hip flexors"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use when developing midfielders' positional discipline in a structured formation — especially in sessions that work on the vertical shape between defenders, midfielders, and attackers. Shows clearly when midfielders drift out of their zone.",
        where_on_pitch: "The middle third — locked between both penalty areas. The constraint forces midfielders to make every pass count within their zone rather than drifting freely, mirroring the positional demands of most tactical systems.",
      },
      {
        id: "eng_md_05",
        name: "Three-Channel Tight Turning",
        duration: "15 mins",
        category: "Technical",
        description: "Receive a pass inside a small central vertical channel under tight pressure. Keep a tight turning circle, use an outside hook or Cruyff turn to escape interference, and pass to create width.",
        football_benefit: "The central channel is the most congested area on any pitch. Midfielders who can receive and escape tight spaces in a split second give their team an instant advantage exactly where the game is decided.",
        instructions: [
          "Mark three parallel channels each 5 yards wide using cones — 15 yards long each",
          "Midfielder plays in the central channel; one defender mirrors them inside it",
          "Server plays a firm pass into the midfielder's feet from one end",
          "Midfielder must turn inside the channel: Cruyff, outside hook, or body feint — choose one",
          "After turning, pass to a target player at the far end of the channel",
          "5 turns in the central channel — then move to the wide channels",
          "Progress: add a second defender to make the channel more congested",
        ],
        success_feels_like: "The defender plants their foot expecting one direction — but you are already facing the other way and the ball is gone. The turn happens in one touch, in zero space, with zero hesitation.",
        gemini_scores: ["Turn Technique", "Touch Tightness", "Acceleration After Turn", "Disguise Quality"],
        equipment_tier: "zero",
        position_tags: ["Midfielder", "Winger", "Striker"],
        muscles_targeted: ["Hip flexors", "Core", "Ankle stabilisers", "Calves"],
        difficulty_level: 3,
        is_premium: true,
        when_to_use: "Use when opposition pressing forces the ball into the central corridor and the midfielder must turn quickly under heavy pressure. Key in any session where the team is working on how to break a press without going long.",
        where_on_pitch: "The central channel of the pitch — the narrow lane between the two fullback positions, directly through the centre circle. This is the most congested zone in any compact defensive shape and where most ball losses occur.",
      },
    ],
  },

  defender: {
    title: "Defensive Unit & Fullback Track",
    focus: "Defensive approach angles, arm's-length pressure, deceleration braking, and line cover support.",
    drills: [
      {
        id: "eng_df_01",
        name: "Angled Pressing & Directional Dictation",
        duration: "15 mins",
        category: "Technical",
        description: "Approach a perimeter attacker at an angle rather than straight-on to limit their options. Get within arm's-length to apply high pressure and dictate their movement toward the wide sidelines.",
        football_benefit: "Defenders who run straight at attackers are easy to beat. An angled approach cuts off the dangerous inside option immediately — forcing attackers where YOU want them to go rather than where they want to be.",
        instructions: [
          "Place a wide attacker cone 20 yards from a full-back starting position on the touchline side",
          "Server plays a pass into the attacker who turns to face goal",
          "Defender sprints but angles the run to cut off the inside pass option first",
          "Get within arm's-length before the attacker has looked up",
          "Show the attacker outward toward the touchline — body angle blocks the inside",
          "Hold jockeying position — do NOT dive in unless attacker shows the ball forward too far",
          "10 reps per side — alternate left side and right side approach angles",
        ],
        success_feels_like: "You arrive at arm's-length before the attacker has made their decision. Your body angle has already removed one option entirely. You feel in control, not reactive — the attacker has no choice but to go where you want.",
        gemini_scores: ["Approach Angle", "Closing Speed", "Jockeying Stance", "Defensive Body Width"],
        equipment_tier: "zero",
        position_tags: ["Defender", "Fullback", "Midfielder"],
        muscles_targeted: ["Quadriceps", "Glutes", "Core", "Ankle stabilisers"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use whenever an attacker receives a wide pass and turns to face your goal — the exact moment a defender must react. Key in sessions on high pressing or defensive organisation on the flanks.",
        where_on_pitch: "Wide defensive channels — the 15-yard strip between the touchline and the edge of the penalty area on each flank. Particularly the transition zone from your own half into the attacking third where wingers and full-backs duel.",
      },
      {
        id: "eng_df_02",
        name: "Cover and Recover Horizontal Channels",
        duration: "15 mins",
        category: "Tactical",
        description: "Work in tandem inside a pitch split horizontally into thirds. Establish optimal supporting distances between the pressing and covering players; if the primary presser is bypassed, the covering player steps out immediately.",
        football_benefit: "Defending is never a solo job. The communication and positioning between a presser and their cover is what makes a defence hard to break — two defenders working together are far more effective than two playing independently.",
        instructions: [
          "Divide a 40×25 pitch into three horizontal thirds using cones",
          "Work in defending pairs: one player presses the ball, the other provides cover 8–10 yards behind",
          "Server plays passes to 3 attackers who attempt to advance through the thirds",
          "When the pressing defender is bypassed, the covering defender steps up immediately",
          "The bypassed defender recovers to become the new cover player — no standing and watching",
          "Communicate constantly: 'Press!', 'Cover!', 'Step!', 'Hold!'",
          "Play 5-minute rounds — aim for 0 goals conceded per round",
        ],
        success_feels_like: "When your partner gets beaten you have already stepped up — because you read the play two passes early. The attackers feel like they're running into a second wall just when they thought they were free.",
        gemini_scores: ["Cover Distance", "Step-Up Timing", "Verbal Communication", "Recovery Run Angle"],
        equipment_tier: "zero",
        position_tags: ["Defender", "Midfielder"],
        muscles_targeted: ["Quadriceps", "Glutes", "Core", "Hip flexors"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use in sessions focused on defensive shape and communication — when your team is working on how the pressing player and the covering player coordinate rather than both pressing or both sitting. Most valuable early in a defensive organisation block.",
        where_on_pitch: "The defensive half — from your own penalty area extending to the halfway line. Defenders operate in a horizontal band, shifting as one unit as the ball moves between the three attackers across the width of the pitch.",
      },
      {
        id: "eng_df_03",
        name: "Line Cover and Press 2v2",
        duration: "20 mins",
        category: "Tactical",
        description: "Small-sided area with mini-goals behind a baseline. One player presses the ball while the other provides deep covering support directly in front of the goal mouth.",
        football_benefit: "The hardest defensive situation is two vs two on goal. This drill builds the instinctive split-second decision between pressing and protecting — the choice that determines whether you concede or not.",
        instructions: [
          "Set up a 30×20 yard area with a full-size goal and keeper at one end",
          "Two defenders start from the goal line — two attackers start from the halfway mark",
          "Coach serves a ball to one attacker to begin each round",
          "Press player attacks the ball holder — cover player drops to protect space in front of goal",
          "When the ball is switched, roles reverse instantly — press follows ball, cover holds shape",
          "If attackers lose the ball, defenders immediately transition and can score on counter",
          "Rotate all roles every 4 minutes — play 20 minutes total",
        ],
        success_feels_like: "You and your partner feel like one unit. You talk constantly and respond instantly. Attackers are frustrated because as soon as they beat one of you, the other is already in position to cover the space.",
        gemini_scores: ["Press Decision Speed", "Cover Positioning Depth", "Role Transition Speed", "Communication Quality"],
        equipment_tier: "basic",
        position_tags: ["Defender", "Midfielder"],
        muscles_targeted: ["Quadriceps", "Core", "Glutes", "Hip flexors"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use in sessions on defensive transition — specifically the moment a through-ball is played and two attackers are bearing down on two defenders. Also for counter-attack defence drills.",
        where_on_pitch: "From the edge of your penalty area back to the goal line — the defensive third where 2v2 situations are most dangerous. One defender presses the ball while the other protects the space directly in front of goal.",
      },
      {
        id: "eng_df_04",
        name: "Stadium Game 1v1 Marking",
        duration: "15 mins",
        category: "Technical",
        description: "Pair up with an opponent inside an isolated half of a 30x20-yard area. Stay close to prevent them from receiving easily, position goal-side, and use a side-on stance to steal possession.",
        football_benefit: "Every great attacker will find themselves 1v1 at some point. The difference between good and great defenders is the discipline to stay goal-side, use a side-on stance, and delay rather than dive — making those instincts automatic.",
        instructions: [
          "Pair up in a 30×20 yard area split into two halves with cones",
          "Maintain goal-side position of your attacker at all times — never let them between you and goal",
          "Use a side-on stance: shoulder to the attacker's shoulder, never square",
          "When the attacker receives from the server, shadow their movement — do NOT dive in",
          "Force them wide and away from central dangerous space — deny the turn",
          "Only attempt to win the ball when attacker shows it too far ahead or commits both feet",
          "5-minute rounds — aim: 0 goals conceded, 2+ possessions won",
        ],
        success_feels_like: "You are patient and controlled. You do not panic when the attacker feints. You stay on your feet, keep side-on, and force them toward the touchline. Then — the moment they show the ball — you take it.",
        gemini_scores: ["Goal-Side Positioning", "Side-On Stance", "Jockeying Patience", "Tackle Timing"],
        equipment_tier: "zero",
        position_tags: ["Defender", "Fullback"],
        muscles_targeted: ["Quadriceps", "Glutes", "Core", "Ankle stabilisers"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use in 1v1 defending sessions — any time a defender must track an attacker who receives in open space behind the midfield. Especially important before matches against teams who play fast wingers or isolated strikers.",
        where_on_pitch: "The defensive third and around the edge of the penalty area — from the 18-yard box out to about 30 yards from goal. The wide defensive channels on either flank where fullbacks most commonly face 1v1 situations.",
      },
      {
        id: "eng_df_05",
        name: "Five-Section Possession Grid",
        duration: "20 mins",
        category: "Tactical",
        description: "Engage in parallel 1v1 duels inside a 30x20-yard pitch split into five sections. Work together as a compact unit off the ball to mark, cover, and intercept passes.",
        football_benefit: "Defensive compactness is built in training, not in matches. This drill forces defenders to think as a unit — maintaining shape, closing gaps, and winning the ball together rather than chasing individually.",
        instructions: [
          "Divide a 30×20 pitch into 5 equal vertical sections using cones",
          "Defenders play in parallel 1v1 matchups — one defender per section",
          "Attackers pass the ball between sections; defenders cannot enter adjacent sections",
          "When ball is in your section, engage your attacker tightly and win the ball",
          "When ball leaves your section, immediately compact toward it — all five shift together",
          "First team to 5 interceptions wins the round",
          "Progress: allow attackers to switch positions to test defensive tracking",
        ],
        success_feels_like: "Your defensive line moves as one organism. When the ball goes left, you all shift left in unison — no gaps appear. Attackers can't find a free player because every time they pass, a defender is already waiting.",
        gemini_scores: ["Defensive Compactness", "Shift Timing", "1v1 Body Position", "Interception Timing"],
        equipment_tier: "zero",
        position_tags: ["Defender", "Midfielder"],
        muscles_targeted: ["Core", "Glutes", "Quadriceps", "Ankle stabilisers"],
        difficulty_level: 3,
        is_premium: true,
        when_to_use: "Use when training defensive shape against a possession-heavy team that circulates the ball patiently. Key in sessions that work on the collective defensive block — how all five defenders shift together as one unit.",
        where_on_pitch: "A compact mid-block position — the five vertical sections span the full width of the pitch, roughly between your own penalty area edge and the halfway line. Defenders hold a narrow 30-yard deep defensive band and shift horizontally together.",
      },
    ],
  },

  goalkeeper: {
    title: "Goalkeeper Elite Protocol",
    focus: "Balls-of-feet readiness, handling holds ('W' and 'M' catch styles), low ground diving, and wide distribution.",
    drills: [
      {
        id: "so_gk_01",
        name: "Ground Side-Diving & Ball Recovery",
        duration: "15 mins",
        category: "Technical",
        description: "Crouch to lower your center of gravity before diving on the side of your body. Get both hands to the ball using the secure 'M' little-finger line for low shots, then immediately hug it into your chest.",
        football_benefit: "Most grassroots goals are scored low and to the side. A goalkeeper who dives confidently, secures with both hands, and instantly smothers the ball eliminates the most common scoring opportunity in every match.",
        instructions: [
          "Stand in ready position: balls of feet, slight knee bend, hands at waist height open",
          "Server kneels 5 yards away and rolls the ball firmly to your left or right",
          "Drop your body weight toward the ball — lead with your bottom hip, not your shoulder",
          "Reach both hands simultaneously: lead hand behind the ball, trailing hand on top",
          "Form the 'M' shape with little fingers meeting beneath low balls",
          "Smother the ball into your chest immediately on contact",
          "Recover to your feet as quickly as possible before the next ball",
          "10 dives each side with 20-second recovery — alternate left and right throughout",
        ],
        success_feels_like: "You hit the ground and the ball is already secured in your hands before you land fully. Both hands moved at the same time. Recovery is instant — you're back on your feet before the striker can react to the rebound.",
        gemini_scores: ["Dive Technique", "Hand Position (M grip)", "Body Shape", "Recovery Speed"],
        equipment_tier: "basic",
        position_tags: ["Goalkeeper"],
        muscles_targeted: ["Core", "Shoulders", "Hip flexors", "Wrists"],
        difficulty_level: 1,
        is_premium: false,
        when_to_use: "Use at the start of every goalkeeper session as fundamental technique work. Also essential before any match where the opposition are known to shoot low and hard from distance or inside the box.",
        where_on_pitch: "Anywhere inside and around the six-yard box — low shots arrive here from close range drives, deflections, and penalty area scrambles. The technique applies to any shot beneath knee height regardless of distance.",
      },
      {
        id: "so_gk_02",
        name: "The 'W' & 'M' Handling Fundamentals",
        duration: "10 mins",
        category: "Technical",
        description: "Practice forming a 'W' with your thumbs almost touching to secure incoming high balls, and an 'M' with little fingers touching to handle low balls. Stand lightly on the balls of your feet with hands open at waist height.",
        football_benefit: "Dropped catches lead directly to goals. The W and M hand positions are the technical foundation of every clean catch — high balls, low shots, everything. Ingraining these shapes means fewer spills under real match pressure.",
        instructions: [
          "Stand facing a server 8 yards away — start with hands in ready position",
          "Server varies delivery: high above the head, mid-height chest, low below the knee",
          "For HIGH balls: thumbs almost touch behind the top of the ball — 'W' shape",
          "For LOW balls: little fingers almost touch beneath the ball — 'M' shape",
          "Call out 'W!' or 'M!' out loud as you catch — builds the decision-making habit under pressure",
          "Do 5 high, 5 mid-height, 5 low balls per round — complete 3 rounds",
          "Progress: server adds a slight fake movement before delivering each ball",
        ],
        success_feels_like: "Your hands form the correct shape automatically before the ball arrives. High ball — thumbs meet. Low shot — little fingers meet. You never even think about it. The ball goes into your hands as if it was magnetised.",
        gemini_scores: ["W Grip Position", "M Grip Position", "Ready Stance", "Catch Security"],
        equipment_tier: "basic",
        position_tags: ["Goalkeeper"],
        muscles_targeted: ["Wrists", "Forearms", "Shoulders", "Core"],
        difficulty_level: 1,
        is_premium: false,
        when_to_use: "Use at the opening of every goalkeeper training session — this is the fundamental technical foundation before any other work. Especially important before matches featuring opponents known for varied delivery — high corners, driven shots, cutbacks.",
        where_on_pitch: "Anywhere in and around the goalkeeper's reach — from the six-yard line to the penalty spot for high deliveries, to the edge of the area for long-range shots. The two hand positions apply to every aerial and ground ball the keeper faces.",
      },
      {
        id: "eng_gk_03",
        name: "Circular Target-Gate Angle Coverage",
        duration: "15 mins",
        category: "Technical",
        description: "Position inside standalone square keeper boxes placed symmetrically within a circle layout. Move dynamically to adjust your positioning angle relative to passing pairs, making safe interceptions on first-time pass inputs.",
        football_benefit: "Goalkeepers who hold the correct angle between ball and far post give shooters far less space. This drill trains the automatic footwork and repositioning needed every time the ball moves around the final third.",
        instructions: [
          "Place 4 cone-goals (2×2 yard each) symmetrically in a circle 20 yards across",
          "Goalkeeper stands in the centre of the circle in ready position",
          "4 servers stand at each cone-goal — one holds the ball at all times",
          "Ball moves between servers via passes — goalkeeper continuously readjusts their angle",
          "Any server can shoot at any time — keeper must be on correct angle when ball arrives",
          "Coach counts goals conceded across 10 minutes",
          "Progression: increase passing speed so footwork must be faster",
        ],
        success_feels_like: "Your feet never stop moving. As the ball shifts around the circle, you are already repositioning — always halfway between the ball and the far post. Shooters find much less space than they expected.",
        gemini_scores: ["Angle Positioning", "Footwork Speed", "Ready Position", "Reaction Time"],
        equipment_tier: "basic",
        position_tags: ["Goalkeeper"],
        muscles_targeted: ["Calves", "Ankle stabilisers", "Core", "Hip flexors"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use when the ball is moving quickly around the final third and the keeper must constantly reposition — for example, during wide ball circulation, crossing situations, or when attackers are playing one-twos around the penalty area.",
        where_on_pitch: "The penalty area and the zone directly in front of goal — roughly a 20-yard arc from post to post. The keeper must stay on the correct line between the ball and the far post at all times as the ball rotates around the circle.",
      },
      {
        id: "eng_gk_04",
        name: "Feeder-Attacker Isolation Guard",
        duration: "15 mins",
        category: "Tactical",
        description: "Manage angle coverage in a 20x15-yard pitch with a goal at one end. Direct your defender to mark the attacker tight, tracking the ball from the feeder, and be alert to make reflex saves.",
        football_benefit: "Most goals come from the combination of a pass plus a finish — not individual skill alone. This drill trains goalkeepers to read the ball, direct the defender, and react to the final shot as one connected sequence.",
        instructions: [
          "Set up a 20×15 yard pitch with a full-size goal at one end — goalkeeper, defender, attacker, feeder",
          "Feeder plays balls from outside the area: ground pass, lifted ball, ball to feet, ball over the top",
          "Goalkeeper calls 'Step!' (defender closes) or 'Hold!' (defender stays) based on the incoming ball",
          "When attacker receives, they go 1v1 on the keeper — defender cannot tackle from behind",
          "Keeper must stay on their toes and react to both the feeder and the attacker simultaneously",
          "Rotate all positions every 5 minutes — play 20 minutes total",
        ],
        success_feels_like: "You direct your defender like a conductor and they listen. When the feeder switches direction you've already called it. The attacker has nowhere to put the ball because your angle has left them no clear target.",
        gemini_scores: ["Communication Quality", "Angle Adjustment Speed", "Save Technique", "Defender Direction Clarity"],
        equipment_tier: "basic",
        position_tags: ["Goalkeeper"],
        muscles_targeted: ["Core", "Shoulders", "Hip flexors", "Ankle stabilisers"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use in sessions focused on goalkeeping communication — specifically when the team is working on how the keeper and last defender coordinate under pressure. Key before matches against teams that use a target forward and feeder combination.",
        where_on_pitch: "Inside the penalty box from the six-yard line out to the penalty spot — the killing zone where through-balls meet finishing runs. The keeper must read the feed, call the defender, and react to the 1v1 all within a 20×15 yard box.",
      },
      {
        id: "eng_gk_05",
        name: "Asymmetric Low Block Clearing",
        duration: "20 mins",
        category: "Tactical",
        description: "Defend a full-size goal with a backline of 8 outfielders against 7 attackers on half a pitch. Dominate your box, collect loose crosses, and quickly distribute wide after a rebound.",
        football_benefit: "Commanding crosses and distributing quickly turns defence into the first moment of attack. This drill builds the courage to come and claim, the communication to organise a backline, and the accuracy to distribute wide immediately.",
        instructions: [
          "Set up on half a pitch: 8 defenders behind the goalkeeper's line vs 8 attackers",
          "Attackers play crosses, through-balls, and combinations into the penalty area",
          "Goalkeeper must call 'KEEPER!' loud and early before attempting to claim or punch any cross",
          "After claiming, distribute immediately — throw wide to the nearest open player",
          "Goalkeeper organises the defensive shape constantly — no silent goalkeepers",
          "Score: +1 per clean claim with distribution, −1 per goal conceded",
          "Play 20 minutes — top scorer of the 'GK index' wins",
        ],
        success_feels_like: "The cross is still in the air and you are already moving forward to claim it. Your call is early and loud and it parts the defenders. You catch it cleanly and the ball is already thrown wide before the attack can reorganise.",
        gemini_scores: ["Cross Claiming Technique", "Claim Call Timing", "Distribution Accuracy", "Box Command"],
        equipment_tier: "basic",
        position_tags: ["Goalkeeper"],
        muscles_targeted: ["Shoulders", "Core", "Calves", "Hip flexors"],
        difficulty_level: 3,
        is_premium: true,
        when_to_use: "Use when training against wide teams that deliver many crosses per match — particularly before cup games or against opponents with pace on the flanks. Also great as the final block of any session to build aerial dominance habits.",
        where_on_pitch: "The penalty area and six-yard box — the high-traffic aerial battleground. The keeper commands a zone stretching from post to post and out to approximately 12 yards, claiming anything that enters that space before attackers can reach it.",
      },
    ],
  },

  winger: {
    title: "Winger & Wide Forward Track",
    focus: "Explosive width, 1v1 isolation, low cross delivery, and recovery tracking.",
    drills: [
      {
        id: "grs_wn_01",
        name: "Wide Channel Sprint & Cross",
        duration: "15 mins",
        category: "Technical",
        description: "Sprint into the wide channel, receive a pass, and deliver a low driven cross before the defender closes. Vary between near-post and cutback deliveries.",
        football_benefit: "A winger who can reliably deliver dangerous low crosses is a coach's dream. The decision between a near-post drive, a cutback, or a far-post lofted ball decides whether a chance is created — this drill makes all three instinctive.",
        instructions: [
          "Mark a 40-yard channel 10 yards wide on one side of the pitch",
          "Server plays a pass into the channel from the edge of the centre circle",
          "Sprint to receive the ball in the wide channel — take at most 2 touches before the cross",
          "A cone 'defender' marks the edge of the penalty area — deliver before reaching it",
          "Vary each cross: near-post driven, cutback to the penalty spot, far-post lofted",
          "10 deliveries per side — coach scores 0 (off target), 1 (on target), 2 (scoring zone)",
          "Progress: add a live defender to close you down",
        ],
        success_feels_like: "Your first touch opens your body and sets up the cross in one motion. You decided near-post before the ball reached you. The delivery is low, flat, and fast — exactly where attackers want it and exactly where keepers hate it.",
        gemini_scores: ["First Touch Open Up", "Cross Technique", "Delivery Accuracy", "Decision (near/far/cutback)"],
        equipment_tier: "basic",
        position_tags: ["Winger", "Fullback"],
        muscles_targeted: ["Quadriceps", "Hip flexors", "Calves", "Core"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use when the team is working on wide attacking transitions — particularly in sessions on quick breaks and final-third delivery after winning the ball centrally. Also ideal when training the overlapping fullback to time their run into the channel.",
        where_on_pitch: "The wide attacking channel — the 10-yard strip between the touchline and the edge of the penalty area on either flank, from the halfway line down to the byline. The delivery must come before the cone/defender at the penalty area edge.",
      },
      {
        id: "grs_wn_02",
        name: "1v1 Isolation Wing Attack",
        duration: "15 mins",
        category: "Technical",
        description: "Start 15m from the full-back. Use a feint to commit them, then accelerate past. Finish by crossing or cutting inside. Best of 5 runs.",
        football_benefit: "The best wingers can beat their defender repeatedly — not just once. This drill builds the change of direction, body feint, and explosive first step that makes a fullback's afternoon miserable from the first minute.",
        instructions: [
          "Set up a 25-yard channel — winger starts 15m from the fullback position",
          "Server plays ball to winger's feet — winger takes one touch to set up the duel",
          "Use one feint or step-over to shift the defender's weight to one side",
          "Accelerate past the defender on the opposite side immediately",
          "If you go outside: deliver a cross; if you cut inside: shoot or play to a striker",
          "Best of 5 runs each side — alternate inside and outside every run",
          "Progress: add a live fullback allowed to foul to build match realism",
        ],
        success_feels_like: "The feint gets the defender's weight on the wrong foot. The acceleration out of the feint is explosive — by the time they have corrected, you have a yard on them. That is all a winger needs.",
        gemini_scores: ["Feint Technique", "Weight Transfer", "Acceleration First Step", "Final Ball Decision"],
        equipment_tier: "zero",
        position_tags: ["Winger", "Striker"],
        muscles_targeted: ["Hip flexors", "Quadriceps", "Glutes", "Calves"],
        difficulty_level: 2,
        is_premium: false,
        when_to_use: "Use as an isolation duel session — when the winger needs to improve their 1v1 ability without combining. Particularly valuable before matches where the opposition's fullback is physically strong and tends to double up with cover.",
        where_on_pitch: "The wide attacking flank — from approximately 25 yards out to the byline on either wing, within 15 yards of the touchline. The duel plays out along the channel where wingers and fullbacks regularly face each other in live match situations.",
      },
      {
        id: "grs_wn_03",
        name: "Recovery Run Tracking",
        duration: "12 mins",
        category: "Physical",
        description: "After losing possession in the final third, sprint back to get goal-side of the ball within 5 seconds. Coach rates effort with 1–3. Target average above 2.5.",
        football_benefit: "Modern wingers don't just attack — they defend too. A winger who tracks back consistently gives their fullback the confidence to overlap, which creates more attacking opportunities. Coaches at every level watch this closely.",
        instructions: [
          "Start at the opponent's corner flag — simulate having just delivered a cross",
          "Coach blows whistle to signal loss of possession",
          "Sprint immediately goal-side — target: level with the ball within 5 seconds",
          "Coach rates your recovery effort: 1 (slow start), 2 (good effort), 3 (outstanding)',",
          "Repeat 10 times alternating left and right touchlines",
          "Average score target: above 2.5 across the 10 reps",
          "Progress: add a live tracker you must beat in the recovery race",
        ],
        success_feels_like: "The moment possession is lost, your hips are already turning. Not a slow rotation — an instant burst of acceleration. By the time the ball is played forward, you are already goal-side and the danger is neutralised.",
        gemini_scores: ["Reaction to Loss", "Recovery Run Speed", "Body Turn Efficiency", "Final Position Accuracy"],
        equipment_tier: "zero",
        position_tags: ["Winger", "Midfielder"],
        muscles_targeted: ["Quadriceps", "Glutes", "Hip flexors", "Calves"],
        difficulty_level: 1,
        is_premium: false,
        when_to_use: "Use immediately after any attacking action where possession is lost — teaches the instant mental switch from attack to defence. Especially powerful mid-session as a consequence drill: miss a cross, immediately sprint back.",
        where_on_pitch: "Diagonally across the pitch — from the opponent's corner flag back to a goal-side position behind the ball, covering approximately 40 yards. The winger must track from the highest attacking position back to a central defensive shape.",
      },
      {
        id: "grs_wn_04",
        name: "Overlap Combination Triangle",
        duration: "20 mins",
        category: "Tactical",
        description: "3-player combination: winger, full-back, striker. Winger plays inside and then overlaps to receive in behind. Finish with a first-time cross or cut-back.",
        football_benefit: "The most dangerous attacking pattern in modern football is the winger-fullback-striker triangle. When all three connect at the right moment, defences collapse — this drill makes the timing feel natural and automatic.",
        instructions: [
          "Set up a triangle: winger wide, fullback behind, striker central — 20×15 yard working area",
          "Winger plays inside to the striker and IMMEDIATELY makes an overlapping run down the outside",
          "Do not wait — the overlap run starts the moment the ball leaves your foot",
          "Striker holds up play briefly then slips the ball into the overlapping winger's run",
          "Winger delivers a first-time cross or cutback for the striker's late run into the box",
          "Rotate positions after every 3 combinations — everyone plays every role",
          "Progress: add a defender to track the overlapping run",
        ],
        success_feels_like: "Your overlap run starts the moment the ball leaves your foot to the striker. You don't wait to see if they control it. By the time it's laid off, you are already in behind and the fullback hasn't even begun to track.",
        gemini_scores: ["Overlap Run Timing", "Pass Accuracy", "Cross Delivery", "Combination Flow"],
        equipment_tier: "zero",
        position_tags: ["Winger", "Fullback", "Striker"],
        muscles_targeted: ["Quadriceps", "Hip flexors", "Calves", "Core"],
        difficulty_level: 3,
        is_premium: true,
        when_to_use: "Use in sessions building attacking width — when the fullback-winger-striker triangle is the main attacking pattern. Perfect for sessions where the team is learning to time overlapping runs and not just dribble wide.",
        where_on_pitch: "The wide corridor from your own half through to the attacking third — spanning about 30 yards diagonally from the centre circle to the byline. All three players in the triangle operate in different vertical zones of this wide channel simultaneously.",
      },
      {
        id: "grs_wn_05",
        name: "Cutback Decision Rondo",
        duration: "15 mins",
        category: "Tactical",
        description: "Reach the byline and choose between a near-post cutback, far-post driven cross, or pulling back to the penalty spot runner. Defenders rotate. 3 points for a first-time finish.",
        football_benefit: "Reaching the byline is only worth something if the delivery creates a chance. The cutback decision is the most valuable last-second choice a winger makes — scanning for the right target before getting there is what separates good wingers from great ones.",
        instructions: [
          "Set up a 20×10 yard rondo area adjacent to the byline",
          "Winger plays through the rondo until they find a channel and reach the byline",
          "Before reaching the byline, look up to identify: near-post runner, penalty spot runner, far-post",
          "Choose one delivery: near-post cutback, far-post driven cross, or penalty spot pullback",
          "Three target players rotate into each zone — score 1 point per accurate delivery, 3 for first-time finish",
          "Defending players rotate out every 3 minutes",
          "Play 15 minutes — highest delivery points total wins",
        ],
        success_feels_like: "You look up before you get to the byline — not at it. You see the penalty spot runner arriving late and the near post unmarked. One look, one decision, and you deliver it exactly where you planned before the ball even reached you.",
        gemini_scores: ["Pre-Delivery Scan", "Cutback Technique", "Cross Zone Accuracy", "Decision Quality"],
        equipment_tier: "basic",
        position_tags: ["Winger", "Striker"],
        muscles_targeted: ["Hip flexors", "Quadriceps", "Core", "Ankle stabilisers"],
        difficulty_level: 3,
        is_premium: true,
        when_to_use: "Use as the decision-making climax of any wide attacking session — after the winger has already worked on 1v1 isolation and crossing, add this to train the final read before the delivery. The payoff drill for any crossing session.",
        where_on_pitch: "The byline area — the last 5 yards before the goal line, from the corner flag in to the near post. The delivery decision is made here: near-post cutback, penalty spot pullback, or driven far-post cross — each going to a different zone.",
      },
    ],
  },
};
