// src/lib/performance-tracker.ts
// Reads biometric scan history from localStorage and computes performance trends.

export interface SessionMetrics {
  overallForm: number;
  explosivePower: number;
  symmetryScore: number;
}

export interface SessionRecord {
  sessionId: string;
  timestamp: string;
  sport: string;
  metrics: SessionMetrics;
}

export interface PlayerPerformance {
  playerName: string;
  sport: string;
  position: string;
  totalSessions: number;
  averages: {
    overallForm: number;
  };
  trends: {
    improvementRate: number;
    consistencyScore: number;
  };
  sessions: SessionRecord[];
}

interface RawScanEntry {
  sessionId?: string;
  timestamp?: string;
  playerId?: string;
  playerName?: string;
  sport?: string;
  position?: string;
  score?: number;
  asymmetry_score?: number;
  explosivePower?: number;
  symmetryScore?: number;
}

const STORAGE_KEY = 'gs_biometric_scans';

export function getStoredSessions(playerId: string): RawScanEntry[] {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const all: RawScanEntry[] = JSON.parse(raw);
    if (!Array.isArray(all)) return [];
    // If entries are tagged with a playerId, filter; otherwise return all
    const filtered = all.filter((e) => !e.playerId || e.playerId === playerId);
    return filtered;
  } catch {
    return [];
  }
}

export function calculatePerformanceTrends(sessions: RawScanEntry[]): PlayerPerformance | null {
  if (!sessions.length) return null;

  const latest = sessions[sessions.length - 1];

  const mapped: SessionRecord[] = sessions.map((s, i) => ({
    sessionId: s.sessionId ?? String(i),
    timestamp: s.timestamp ?? new Date().toISOString(),
    sport: s.sport ?? 'Football',
    metrics: {
      overallForm:    Math.round(s.score ?? 50),
      explosivePower: Math.round(s.explosivePower ?? 50),
      symmetryScore:  Math.round(100 - (s.asymmetry_score ?? 0)),
    },
  }));

  const avgForm = Math.round(
    mapped.reduce((sum, s) => sum + s.metrics.overallForm, 0) / mapped.length
  );

  // Improvement rate: compare first half avg vs second half avg
  const mid = Math.floor(mapped.length / 2);
  const firstHalf  = mapped.slice(0, mid || 1);
  const secondHalf = mapped.slice(mid);
  const firstAvg  = firstHalf.reduce((s, r) => s + r.metrics.overallForm, 0) / firstHalf.length;
  const secondAvg = secondHalf.reduce((s, r) => s + r.metrics.overallForm, 0) / secondHalf.length;
  const improvementRate = Math.round(((secondAvg - firstAvg) / Math.max(firstAvg, 1)) * 100);

  // Consistency: stddev-based score
  const mean = avgForm;
  const variance = mapped.reduce((sum, s) => sum + Math.pow(s.metrics.overallForm - mean, 2), 0) / mapped.length;
  const stddev = Math.sqrt(variance);
  const consistencyScore = Math.max(0, Math.round(100 - stddev));

  return {
    playerName:    latest.playerName ?? 'Player',
    sport:         latest.sport     ?? 'Football',
    position:      latest.position  ?? 'Unknown',
    totalSessions: mapped.length,
    averages:      { overallForm: avgForm },
    trends:        { improvementRate, consistencyScore },
    sessions:      mapped.slice().reverse(),
  };
}

export function exportScoutReport(performance: PlayerPerformance): string {
  const lines = [
    `GRASSROOTS SPORTS — SCOUT REPORT`,
    `Player: ${performance.playerName}`,
    `Sport: ${performance.sport}  |  Position: ${performance.position}`,
    ``,
    `PERFORMANCE SUMMARY`,
    `Total Sessions Logged : ${performance.totalSessions}`,
    `Average Form Score    : ${performance.averages.overallForm}/100`,
    `Improvement Rate      : ${performance.trends.improvementRate > 0 ? '+' : ''}${performance.trends.improvementRate}%`,
    `Consistency Score     : ${performance.trends.consistencyScore}%`,
    ``,
    `SESSION HISTORY (latest first)`,
    ...performance.sessions.slice(0, 10).map((s, i) =>
      `${i + 1}. ${new Date(s.timestamp).toLocaleDateString()}  Form: ${s.metrics.overallForm}  Power: ${s.metrics.explosivePower}%  Symmetry: ${s.metrics.symmetryScore}%`
    ),
    ``,
    `Generated by GrassRoots Sports · grassrootssports.live`,
  ];
  return lines.join('\n');
}
