// src/lib/sport-drills.ts
// Drill data for all non-football sports.
// Uses the same DrillData / PositionTrack interfaces as drill-data.ts
// The `football_benefit` field is repurposed as a generic sport benefit description.

import type { DrillData, PositionTrack } from "./drill-data";

export { type PositionTrack };

// ─── Position keys per sport ─────────────────────────────────────────────────

export const SPORT_POSITION_MAP: Record<string, string[]> = {
  football:   ["striker", "midfielder", "defender", "goalkeeper", "winger"],
  rugby:      ["backs", "forwards", "halfback"],
  athletics:  ["sprinter", "endurance", "field"],
  netball:    ["shooter", "centre", "defender"],
  basketball: ["guard", "forward", "center"],
  cricket:    ["batsman", "bowler", "allrounder"],
  swimming:   ["sprint", "endurance", "stroke"],
  tennis:     ["baseline", "serve-volley", "all-court"],
  volleyball: ["setter", "spiker", "libero"],
  hockey:     ["forward", "midfielder", "defender"],
};

// ─── RUGBY ───────────────────────────────────────────────────────────────────

const RUGBY: Record<string, PositionTrack> = {
  backs: {
    title: "Backs Track",
    focus: "Speed, evasion, and ball-handling at pace.",
    drills: [
      {
        id: "rug_bk_01", name: "Side-Step Acceleration", duration: "12 mins",
        description: "Plant your foot hard and explode in the opposite direction. The core evasion skill for all backs.",
        category: "Physical", football_benefit: "Creates line breaks by beating first defenders",
        instructions: ["Mark two cones 5m apart", "Sprint to first cone, plant and step hard left", "Accelerate to second cone at full speed", "Rest 30s — repeat 8x each side"],
        success_feels_like: "Your first step after the plant is faster than your approach.",
        gemini_scores: ["Plant foot angle", "Explosion off plant", "Balance maintained"],
        equipment_tier: "zero", position_tags: ["backs"], muscles_targeted: ["glutes", "quads", "calves"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "rug_bk_02", name: "Catch-Pass at Pace", duration: "15 mins",
        description: "Receive a pass at 80% sprint speed and deliver to a target in 3 steps. Develops clean hands under pressure.",
        category: "Technical", football_benefit: "Clean ball transfer through the backline",
        instructions: ["4 cones in a line, 5m apart", "Passer throws as receiver hits cone 1", "Catch and pass to next target within 3 steps", "Rotate roles every 5 runs"],
        success_feels_like: "The ball sticks first time without breaking your running line.",
        gemini_scores: ["Hand position", "Pass timing", "Running line after pass"],
        equipment_tier: "basic", position_tags: ["backs"], muscles_targeted: ["forearms", "shoulders", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "rug_bk_03", name: "Counter-Attack Decision Sprint", duration: "10 mins",
        description: "Receive a kick simulation, read the defence, and sprint through the nominated gap. Trains broken-play instinct.",
        category: "Tactical", football_benefit: "Turns turnovers into try-scoring opportunities",
        instructions: ["Mark 40m channel with wide cones", "Coach calls 'kick!' — pick ball from ground", "Sprint through coach-nominated gap (changes each rep)", "Touch far cone to finish"],
        success_feels_like: "You're past the defensive line before they reset.",
        gemini_scores: ["Decision speed", "Sprint angle", "Ball security in contact zone"],
        equipment_tier: "basic", position_tags: ["backs"], muscles_targeted: ["hamstrings", "glutes", "core"],
        difficulty_level: 3, is_premium: false,
      },
    ],
  },
  forwards: {
    title: "Forwards Track",
    focus: "Power, body position, and set-piece execution.",
    drills: [
      {
        id: "rug_fw_01", name: "Scrum Drive Against Wall", duration: "15 mins",
        description: "Simulate scrum engagement against a solid surface. Builds leg drive and body angle that wins front-row contests.",
        category: "Physical", football_benefit: "Dominant scrum platform for attacking ball",
        instructions: ["Face wall, feet shoulder-width", "Bind hands on surface, lower hips to 45°", "Drive legs hard for 5 seconds", "Release, reset — repeat x10"],
        success_feels_like: "Your legs do the work — back stays straight throughout.",
        gemini_scores: ["Hip angle at 45°", "Spine alignment", "Leg drive power"],
        equipment_tier: "zero", position_tags: ["forwards"], muscles_targeted: ["quads", "glutes", "lower back", "shoulders"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "rug_fw_02", name: "Tackle & Ball Presentation", duration: "12 mins",
        description: "Hit a bag, go to ground and present the ball correctly above your head. The breakdown skill every forward must own.",
        category: "Technical", football_benefit: "Efficient ball presentation at the ruck",
        instructions: ["Approach tackle bag at half pace", "Make shoulder contact, drive through", "Go to ground, roll onto back", "Present ball above your head with arms extended"],
        success_feels_like: "The ball is free and above your head in one smooth motion.",
        gemini_scores: ["Shoulder height at contact", "Ball security", "Roll completion"],
        equipment_tier: "basic", position_tags: ["forwards"], muscles_targeted: ["shoulders", "core", "triceps"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "rug_fw_03", name: "Lineout Lift Timing", duration: "12 mins",
        description: "Two lifters practice the lift from standing — elevating a jumper smoothly with correct timing and body position.",
        category: "Technical", football_benefit: "Secure lineout possession from throw-ins",
        instructions: ["Jumper stands between two lifters", "Lifters grip thighs and calves", "On signal: lift smoothly, hold 2 seconds", "Lower controlled — never drop — repeat x8"],
        success_feels_like: "Jumper rises vertically with zero wobble.",
        gemini_scores: ["Lift symmetry", "Jumper body position", "Hold stability"],
        equipment_tier: "zero", position_tags: ["forwards"], muscles_targeted: ["quads", "glutes", "biceps", "core"],
        difficulty_level: 3, is_premium: false,
      },
    ],
  },
  halfback: {
    title: "Half-Back Track",
    focus: "Service speed, kicking accuracy, and game control.",
    drills: [
      {
        id: "rug_hb_01", name: "Ruck Service Speed", duration: "15 mins",
        description: "From a simulated ruck, deliver the fastest possible clean service. Time each delivery — target under 1.5 seconds.",
        category: "Technical", football_benefit: "Quick ball that puts backs into space before defence sets",
        instructions: ["Ball on ground, mark target zone 5m away", "Crouch, grab ball, deliver to target", "Time each delivery with a phone", "Target: consistent sub-1.5s service"],
        success_feels_like: "The ball reaches the receiver before the defensive line reads it.",
        gemini_scores: ["Pick-up speed", "Pass trajectory", "Delivery time"],
        equipment_tier: "basic", position_tags: ["halfback"], muscles_targeted: ["forearms", "wrists", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "rug_hb_02", name: "Box Kick Accuracy", duration: "12 mins",
        description: "Kick to a marked 5×5m landing zone 20m away from a simulated scrum base. Both accuracy and hang time are scored.",
        category: "Technical", football_benefit: "Tactical kicks that contest possession in the air",
        instructions: ["Mark 5m × 5m landing zone 20m away", "Receive pass from feeder at scrum base", "Box kick aiming for zone", "10 kicks — count accurate landings"],
        success_feels_like: "Ball hangs long enough for chasers to arrive under it.",
        gemini_scores: ["Contact point on boot", "Follow-through height", "Landing zone accuracy"],
        equipment_tier: "basic", position_tags: ["halfback"], muscles_targeted: ["hip flexors", "quads", "core"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "rug_hb_03", name: "Decision Pass Circuit", duration: "10 mins",
        description: "Coach signals left or right at the last second — you deliver the correct pass at full pace. Pure game-reading speed.",
        category: "Tactical", football_benefit: "Reads the defence and hits the right option instantly",
        instructions: ["Stand between two receivers 6m each side", "Touch ball on the ground", "Coach signals direction as you rise", "Pass accurately to signalled side — repeat x20"],
        success_feels_like: "You're releasing as the signal lands — one fluid movement.",
        gemini_scores: ["Reaction time", "Pass accuracy", "Body shape before signal"],
        equipment_tier: "basic", position_tags: ["halfback"], muscles_targeted: ["shoulders", "forearms", "core"],
        difficulty_level: 3, is_premium: false,
      },
    ],
  },
};

// ─── ATHLETICS ───────────────────────────────────────────────────────────────

const ATHLETICS: Record<string, PositionTrack> = {
  sprinter: {
    title: "Sprinter Track",
    focus: "Block starts, drive phase, and top-end velocity.",
    drills: [
      {
        id: "ath_sp_01", name: "Drive Phase Wall Drill", duration: "10 mins",
        description: "Lean at 45° against a wall and alternate knee drives. Builds the forward lean and power of the first 10 metres.",
        category: "Technical", football_benefit: "Explosive first 10m acceleration off the line",
        instructions: ["Lean hands on wall at 45°", "Drive right knee to hip height, hold 1 second", "Switch legs rapidly — hips stay extended", "30s on / 30s off — 6 sets"],
        success_feels_like: "Your hips stay high and extended throughout the drill.",
        gemini_scores: ["Knee drive height", "Hip extension", "Arm position"],
        equipment_tier: "zero", position_tags: ["sprinter"], muscles_targeted: ["hip flexors", "glutes", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "ath_sp_02", name: "Flying 20m Sprint", duration: "15 mins",
        description: "Build over 20m then hit a fly zone at absolute maximum velocity. Trains top speed without block-start fatigue.",
        category: "Physical", football_benefit: "Maximum velocity speed that separates elite sprinters",
        instructions: ["Mark: start → 20m build zone → 20m fly zone", "Accelerate fully through the build zone", "Sprint the fly zone at 100% effort", "Full walk-back recovery — 5 reps"],
        success_feels_like: "The fly zone feels effortless — legs turning over automatically.",
        gemini_scores: ["Fly zone entry speed", "Stride frequency", "Upper body relaxation"],
        equipment_tier: "zero", position_tags: ["sprinter"], muscles_targeted: ["hamstrings", "glutes", "quads"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "ath_sp_03", name: "Reaction Start Drill", duration: "12 mins",
        description: "Sprint 20m from varied starting positions on an audio signal. Trains sub-200ms gun reaction.",
        category: "Physical", football_benefit: "Sub-200ms reaction time that wins races at the start",
        instructions: ["Use a clap or whistle as start signal", "Vary start position each rep: standing, crouching, seated", "Sprint 20m at 100% on signal", "Record your sharpest felt reaction"],
        success_feels_like: "You are moving before you consciously register the signal.",
        gemini_scores: ["Reaction time", "First step direction", "Starting position efficiency"],
        equipment_tier: "zero", position_tags: ["sprinter"], muscles_targeted: ["glutes", "hamstrings", "calves"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
  endurance: {
    title: "Endurance Track",
    focus: "Pacing, cadence, and aerobic threshold development.",
    drills: [
      {
        id: "ath_en_01", name: "Tempo Threshold Run", duration: "20 mins",
        description: "Run at 75–80% max effort continuously. The foundation of every middle and long-distance runner's training.",
        category: "Physical", football_benefit: "Builds the aerobic engine that sustains race pace to the finish",
        instructions: ["5-min easy warm-up jog", "Run at 'comfortably hard' — can speak 3-word phrases", "Hold this pace for 12–15 minutes", "5-min cool-down walk"],
        success_feels_like: "You finish tired but in control — you could run 5 more minutes.",
        gemini_scores: ["Pace consistency", "Breathing rhythm", "Running economy"],
        equipment_tier: "zero", position_tags: ["endurance"], muscles_targeted: ["quadriceps", "hamstrings", "calves"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "ath_en_02", name: "Cadence Drill", duration: "10 mins",
        description: "Run at exactly 180 steps per minute. Improves ground contact time and running efficiency at any pace.",
        category: "Technical", football_benefit: "Faster leg turnover reduces injury risk and improves economy",
        instructions: ["Easy pace run — count left foot strikes for 30s", "Target: 45 left strikes per 30s (= 180 total spm)", "Use a phone metronome at 180 BPM if available", "Run 4 × 2 min at target cadence"],
        success_feels_like: "Shorter, quicker steps feel smooth rather than choppy.",
        gemini_scores: ["Steps per minute", "Ground contact time", "Vertical oscillation"],
        equipment_tier: "zero", position_tags: ["endurance"], muscles_targeted: ["calves", "tibialis anterior", "hip flexors"],
        difficulty_level: 1, is_premium: false,
      },
      {
        id: "ath_en_03", name: "Hill Repeats", duration: "20 mins",
        description: "Sprint uphill, walk back down. Builds posterior chain power without the joint impact of flat sprinting.",
        category: "Physical", football_benefit: "Power development with reduced joint stress",
        instructions: ["Find a 4–6% gradient hill, 80–100m long", "Sprint uphill at 90% effort", "Walk back down as full recovery", "Repeat 6–10 times"],
        success_feels_like: "Hips drive forward up the hill — minimal backward lean.",
        gemini_scores: ["Forward lean angle", "Knee drive height", "Arm symmetry"],
        equipment_tier: "zero", position_tags: ["endurance"], muscles_targeted: ["glutes", "hamstrings", "calves", "core"],
        difficulty_level: 3, is_premium: false,
      },
    ],
  },
  field: {
    title: "Field Events Track",
    focus: "Approach run, explosive takeoff, and power release.",
    drills: [
      {
        id: "ath_fi_01", name: "Bounding Approach Run", duration: "15 mins",
        description: "Exaggerated long bounds over 20m. Develops horizontal power for long jump and triple jump approach.",
        category: "Physical", football_benefit: "Maximum horizontal power on the approach to takeoff",
        instructions: ["Mark 20m approach zone", "Bound with exaggerated knee lift and arm drive", "Cover maximum distance per stride", "6 runs — 60s rest between each"],
        success_feels_like: "Each bound floats — you feel propelled forward, not falling.",
        gemini_scores: ["Flight time per bound", "Takeoff angle", "Arm drive amplitude"],
        equipment_tier: "zero", position_tags: ["field"], muscles_targeted: ["glutes", "quads", "hip flexors", "calves"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "ath_fi_02", name: "Rotational Power Throw", duration: "12 mins",
        description: "Throw a heavy stone or sand bag with a rotational action. Develops shot put and discus power from the ground up.",
        category: "Physical", football_benefit: "Hip-to-shoulder rotational power for throwing events",
        instructions: ["Stand side-on to target, 2m away", "Hold a stone or heavy bag at hip height", "Rotate hips first — arms follow", "Release and follow through — 10 reps each side"],
        success_feels_like: "Power comes from your hips turning, not your arms pulling.",
        gemini_scores: ["Hip-shoulder separation", "Release angle", "Follow-through completion"],
        equipment_tier: "basic", position_tags: ["field"], muscles_targeted: ["obliques", "glutes", "shoulders", "lats"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "ath_fi_03", name: "Standing Long Jump", duration: "10 mins",
        description: "Jump for maximum distance from a standing position using arm swing and two-footed takeoff. Raw lower-body power test.",
        category: "Physical", football_benefit: "Explosive lower-body power with zero equipment",
        instructions: ["Stand behind line, feet shoulder-width", "Swing arms back then explode forward", "Drive off both feet simultaneously, extend arms", "Mark landing — repeat 10 times"],
        success_feels_like: "Arms and legs peak together — one coordinated unit.",
        gemini_scores: ["Arm-leg coordination", "Hip extension at takeoff", "Landing stability"],
        equipment_tier: "zero", position_tags: ["field"], muscles_targeted: ["quads", "glutes", "calves", "core"],
        difficulty_level: 1, is_premium: false,
      },
    ],
  },
};

// ─── NETBALL ─────────────────────────────────────────────────────────────────

const NETBALL: Record<string, PositionTrack> = {
  shooter: {
    title: "Shooter Track",
    focus: "Shooting accuracy, circle movement, and rebounding.",
    drills: [
      {
        id: "net_sh_01", name: "5-Position Shooting Circuit", duration: "15 mins",
        description: "Shoot from 5 marked spots in the circle. Builds muscle memory for accurate shooting under match pressure.",
        category: "Technical", football_benefit: "Consistent shooting accuracy from all circle angles",
        instructions: ["Mark 5 spots: centre, two sides, two diagonals", "10 shots from each position", "Count goals out of 50", "Focus: eyes on ring, follow through high"],
        success_feels_like: "The ball drops cleanly through the ring — no rim contact.",
        gemini_scores: ["Shooting arc", "Follow-through height", "Foot positioning before shot"],
        equipment_tier: "basic", position_tags: ["shooter"], muscles_targeted: ["shoulders", "triceps", "wrists"],
        difficulty_level: 1, is_premium: false,
      },
      {
        id: "net_sh_02", name: "Dodge & Receive to Shoot", duration: "12 mins",
        description: "Lead, dodge a defender and receive ready to shoot immediately. The movement pattern that creates every clean shooting chance.",
        category: "Tactical", football_benefit: "Creates catch-to-shoot opportunity against tight marking",
        instructions: ["Start outside circle — defender marks", "Lead away, plant hard, dodge back to circle edge", "Receive in balance — shoot immediately", "Reset and repeat 15 times"],
        success_feels_like: "You catch in perfect balance — no correction step needed.",
        gemini_scores: ["Dodge sharpness", "Balance on catch", "Shooting readiness"],
        equipment_tier: "basic", position_tags: ["shooter"], muscles_targeted: ["quads", "glutes", "shoulders"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "net_sh_03", name: "Rebound Positioning", duration: "10 mins",
        description: "Read a missed shot and position to collect for an immediate second attempt. Turns every miss into a scoring opportunity.",
        category: "Tactical", football_benefit: "Converts rebounds into immediate second-shot goals",
        instructions: ["Shooter intentionally misses from various angles", "Goal shooter reads ball spin and moves to collect", "Catch cleanly inside circle — shoot immediately", "Repeat 10 times from each side"],
        success_feels_like: "You collect the rebound already positioned to shoot.",
        gemini_scores: ["Ball trajectory read", "Positioning footwork", "Catch-to-shoot speed"],
        equipment_tier: "basic", position_tags: ["shooter"], muscles_targeted: ["quads", "calves", "core"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
  centre: {
    title: "Centre Track",
    focus: "Court coverage, centre pass, and link play.",
    drills: [
      {
        id: "net_ct_01", name: "Centre Pass Lead", duration: "12 mins",
        description: "Sprint from centre circle on the whistle and receive the centre pass in full stride. The most important centre skill.",
        category: "Technical", football_benefit: "Clean centre pass receipt that launches the attack",
        instructions: ["Start in centre circle — partner holds ball", "On whistle: sprint toward attacking third", "Turn and receive pass in full stride", "Immediately feed a third player — repeat 20 times"],
        success_feels_like: "You receive in full stride — no stopping, no correction.",
        gemini_scores: ["Lead timing", "Catch in stride", "Feed speed after receiving"],
        equipment_tier: "basic", position_tags: ["centre"], muscles_targeted: ["quads", "hamstrings", "shoulders"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "net_ct_02", name: "Baseline-to-Baseline Coverage", duration: "15 mins",
        description: "Sprint baseline to baseline with sharp changes of direction. Simulates the constant court coverage a centre player needs for 60 minutes.",
        category: "Physical", football_benefit: "Sustained court coverage across all four quarters",
        instructions: ["Sprint from baseline to centre circle — touch", "Sprint back to defensive baseline — touch", "Continue for 2 minutes without stopping", "Rest 60s — repeat 5 times"],
        success_feels_like: "Your last sprint is as fast as your first.",
        gemini_scores: ["Speed consistency across sets", "Direction-change sharpness", "Recovery pace"],
        equipment_tier: "zero", position_tags: ["centre"], muscles_targeted: ["quads", "hamstrings", "glutes", "calves"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "net_ct_03", name: "Switch Direction Lead", duration: "10 mins",
        description: "Lead one way at half pace, plant hard and cut the other direction. Makes the defender commit to the wrong side.",
        category: "Tactical", football_benefit: "Creates half-a-step separation through deceptive movement",
        instructions: ["Lead left at half pace for 3 steps", "Plant right foot hard — push sharply right", "Receive pass on new line", "Focus on making the defender commit before you cut"],
        success_feels_like: "The defender commits before you change — you receive unchallenged.",
        gemini_scores: ["Lead deception quality", "Plant foot explosion", "Catch positioning"],
        equipment_tier: "basic", position_tags: ["centre"], muscles_targeted: ["glutes", "hip flexors", "quads"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
  defender: {
    title: "Defender Track",
    focus: "Legal pressure, shadow footwork, and interceptions.",
    drills: [
      {
        id: "net_df_01", name: "Shadow Marking Footwork", duration: "12 mins",
        description: "Stay 0.9m from an attacker and mirror every movement without reaching. Builds pressure that is legal and relentless.",
        category: "Technical", football_benefit: "Legal defensive pressure that disrupts shooting rhythm",
        instructions: ["Pair up in 3m zone — attacker moves freely", "Defender mirrors at 0.9m, hands up — no contact", "Attacker tries to create space — defender stays", "2-minute rounds, then swap"],
        success_feels_like: "Your feet are always angled to cut off the most likely direction.",
        gemini_scores: ["Spacing maintenance", "Foot agility", "Hands position"],
        equipment_tier: "zero", position_tags: ["defender"], muscles_targeted: ["glutes", "quads", "calves", "hip flexors"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "net_df_02", name: "Intercept Reading Drill", duration: "15 mins",
        description: "Read a pass between two attackers and intercept before it arrives. Pure anticipation — move on the passer, not the ball.",
        category: "Tactical", football_benefit: "Turnovers through reading opposition ball movement",
        instructions: ["Two attackers pass at medium pace 6m apart", "Defender stands between them", "Intercept by reading passer body language", "Focus: move before the pass, not after the ball"],
        success_feels_like: "You are moving as the passer's wrist turns — not reacting to the ball.",
        gemini_scores: ["Read timing", "Intercept angle", "Recovery if ball goes past"],
        equipment_tier: "basic", position_tags: ["defender"], muscles_targeted: ["core", "shoulders", "hip flexors"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "net_df_03", name: "0.9m Obstruction Drill", duration: "10 mins",
        description: "Practice landing and immediately adjusting to exactly 0.9m when defending a shooter. Get it wrong and concede a penalty.",
        category: "Technical", football_benefit: "Disciplined marking that maximises legal pressure",
        instructions: ["Shooter catches in circle", "Defender lands and immediately adjusts to 0.9m distance", "Hold hands high — no body lean forward", "Partner calls 'good' or 'too close'"],
        success_feels_like: "You are close enough to put off the shooter but never concede a penalty.",
        gemini_scores: ["Landing adjustment speed", "Spacing accuracy", "Hands height"],
        equipment_tier: "basic", position_tags: ["defender"], muscles_targeted: ["core", "shoulders", "quads"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
};

// ─── BASKETBALL ──────────────────────────────────────────────────────────────

const BASKETBALL: Record<string, PositionTrack> = {
  guard: {
    title: "Guard Track",
    focus: "Ball handling, pull-up shooting, and court vision.",
    drills: [
      {
        id: "bas_gu_01", name: "Crossover Attack Dribble", duration: "12 mins",
        description: "Attack the cone at full speed, low crossover, explode past. Builds the ball-handling that beats first defenders.",
        category: "Technical", football_benefit: "Loses defender with one dribble move to create advantage",
        instructions: ["Set cone 4m away — dribble at full pace", "At cone: low, tight crossover to off-hand", "Accelerate past cone to finish at basket", "Alternate: between-legs and behind-back variations"],
        success_feels_like: "The crossover is low and tight — defender cannot poke the ball free.",
        gemini_scores: ["Dribble height during crossover", "Change-of-direction speed", "Acceleration after move"],
        equipment_tier: "basic", position_tags: ["guard"], muscles_targeted: ["forearms", "quads", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "bas_gu_02", name: "Pull-Up Mid-Range", duration: "15 mins",
        description: "Dribble at pace then stop and shoot off one or two dribbles. The guard's most reliable scoring weapon in a set defence.",
        category: "Technical", football_benefit: "Consistent mid-range scoring over a closing defender",
        instructions: ["Start at half court, dribble hard at the elbow", "Two dribbles — hard stop — jump shot", "Focus: balanced landing, eyes on target before release", "10 reps each elbow — count percentage"],
        success_feels_like: "Your feet are balanced under you before the ball leaves your hands.",
        gemini_scores: ["Footwork on stop", "Shot arc", "Balance at release"],
        equipment_tier: "basic", position_tags: ["guard"], muscles_targeted: ["quads", "shoulders", "wrists"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "bas_gu_03", name: "Full-Court Dribble Pressure", duration: "10 mins",
        description: "Dribble full court at pace using both hands under tight cone pressure. Builds handle under full-court defence.",
        category: "Physical", football_benefit: "Protects the ball against full-court pressing defence",
        instructions: ["Set 6 cones full court in a slalom", "Dribble at 80% pace — stay low through cones", "Alternate: right hand down, left hand back", "Time each run — aim to improve"],
        success_feels_like: "The ball is an extension of your hand — never looks at it.",
        gemini_scores: ["Dribble height", "Change-of-direction sharpness", "Head position (up vs down)"],
        equipment_tier: "basic", position_tags: ["guard"], muscles_targeted: ["forearms", "calves", "core"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
  forward: {
    title: "Forward Track",
    focus: "Face-up game, post entry, and driving lanes.",
    drills: [
      {
        id: "bas_fw_01", name: "Face-Up Triple Threat", duration: "12 mins",
        description: "Catch in triple-threat, read the defender, choose: drive, shot, or pass. The forward's decision-making under pressure.",
        category: "Tactical", football_benefit: "Creates scoring opportunity from every mid-range catch",
        instructions: ["Receive pass facing basket at elbow", "Hold triple-threat position — read imaginary defender", "Coach calls: 'drive left', 'shoot', or 'pass'", "Execute the called option at game speed — 15 reps"],
        success_feels_like: "You read and react in one motion — no hesitation.",
        gemini_scores: ["Triple-threat stance", "Decision speed", "Execution of chosen option"],
        equipment_tier: "basic", position_tags: ["forward"], muscles_targeted: ["core", "quads", "shoulders"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "bas_fw_02", name: "Drop-Step Finish", duration: "15 mins",
        description: "Post catch, drop-step past the defender and finish at the basket. The primary post scoring move at every level.",
        category: "Technical", football_benefit: "Scores from the post against any size defender",
        instructions: ["Catch ball with back to basket", "Feel which side defender is on", "Drop step that foot — seal defender", "Power dribble and finish at basket — 10 each side"],
        success_feels_like: "You feel the defender's weight and move away from it instantly.",
        gemini_scores: ["Pivot foot placement", "Drop step quickness", "Finish at contact"],
        equipment_tier: "basic", position_tags: ["forward"], muscles_targeted: ["glutes", "core", "forearms"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "bas_fw_03", name: "Screen & Roll Timing", duration: "12 mins",
        description: "Set a screen on a cone/partner, hold contact, then roll to basket. Gets the timing right before a real defender reacts.",
        category: "Tactical", football_benefit: "Generates open looks through correct screen-and-roll timing",
        instructions: ["Walk to set screen on cone — stop, feet wide, arms in", "Hold 1 beat — pivot and roll to basket", "Receive pass at roll position and finish", "10 reps — vary screen angle each time"],
        success_feels_like: "Your roll arrives at the basket just as the pass does.",
        gemini_scores: ["Screen contact width", "Roll pivot timing", "Catch-and-finish at roll spot"],
        equipment_tier: "basic", position_tags: ["forward"], muscles_targeted: ["glutes", "core", "shoulders"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
  center: {
    title: "Center Track",
    focus: "Post positioning, rebounding, and finishing at the rim.",
    drills: [
      {
        id: "bas_ce_01", name: "Post Seal & Catch", duration: "12 mins",
        description: "Establish post position against a defender, seal, and catch the entry pass in balance. The foundation of every post game.",
        category: "Technical", football_benefit: "Controls post position to receive ball in scoring range",
        instructions: ["Back to basket, defender behind you", "Use legs to feel defender — seal with hip", "Call for ball, catch with two hands in balance", "Immediately go to your move — 10 reps each side"],
        success_feels_like: "You catch without moving your feet — already in your power position.",
        gemini_scores: ["Hip seal effectiveness", "Catch balance", "Immediate move readiness"],
        equipment_tier: "basic", position_tags: ["center"], muscles_targeted: ["glutes", "core", "quads"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "bas_ce_02", name: "Box-Out Rebounding", duration: "12 mins",
        description: "On a shot, seal your opponent on your back and chase the rebound. Rebounds win games — this is the most trainable skill in basketball.",
        category: "Tactical", football_benefit: "Secures possession after every missed shot",
        instructions: ["Partner takes shot from elbow", "On shot: pivot, find your opponent, put them on your back", "Sprint to ball — catch with two hands at peak", "Outlet pass immediately — repeat 15 times"],
        success_feels_like: "You catch the rebound above your head with no contest.",
        gemini_scores: ["Box-out pivot speed", "Contact maintenance", "Rebound height"],
        equipment_tier: "basic", position_tags: ["center"], muscles_targeted: ["glutes", "core", "shoulders"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "bas_ce_03", name: "Mikan Drill", duration: "10 mins",
        description: "Alternating lay-ups from both sides of the basket without letting the ball touch the ground. The classic finishing drill for big men.",
        category: "Technical", football_benefit: "Soft touch at the rim on both hands",
        instructions: ["Start under the basket", "Lay up with right hand from right side", "Catch before it hits ground, step to left side", "Lay up with left hand — continuous for 60 seconds"],
        success_feels_like: "Both hands finish equally soft — ball rolls gently over the rim.",
        gemini_scores: ["Off-hand finish quality", "Footwork rhythm", "Touch on the glass"],
        equipment_tier: "basic", position_tags: ["center"], muscles_targeted: ["calves", "shoulders", "forearms"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
};

// ─── CRICKET ─────────────────────────────────────────────────────────────────

const CRICKET: Record<string, PositionTrack> = {
  batsman: {
    title: "Batsman Track",
    focus: "Technique, shot selection, and footwork.",
    drills: [
      {
        id: "cri_ba_01", name: "Forward Defensive Repetition", duration: "15 mins",
        description: "Play 50 consecutive forward defensive strokes against a wall or cone, focusing on bat face and pad alignment.",
        category: "Technical", football_benefit: "Solid defensive technique to survive quality bowling",
        instructions: ["Mark a crease line", "Shadow 50 forward defensives — bat face straight", "Focus: front foot to pitch of ball, head over toe", "Coach calls 'no' for any opening in the gate"],
        success_feels_like: "Bat and pad are close together — no gap for the ball to get through.",
        gemini_scores: ["Bat face angle", "Head position over front toe", "Pad alignment"],
        equipment_tier: "zero", position_tags: ["batsman"], muscles_targeted: ["forearms", "core", "quads"],
        difficulty_level: 1, is_premium: false,
      },
      {
        id: "cri_ba_02", name: "Straight Drive Alignment", duration: "12 mins",
        description: "Hit a ball on a string or tee down the ground with a straight bat. The straight drive is the purest shot in batting.",
        category: "Technical", football_benefit: "Drives full deliveries on a good length through the covers",
        instructions: ["Hang ball on string at full-pitch length OR use a tee", "Drive ball straight — aim at a cone at 30 yards", "Focus: high elbow, follow through to cover point", "20 drives — count straight ones"],
        success_feels_like: "The ball travels along the ground straight, not to the left or right.",
        gemini_scores: ["Bat swing path", "High elbow position", "Follow-through direction"],
        equipment_tier: "basic", position_tags: ["batsman"], muscles_targeted: ["forearms", "shoulders", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "cri_ba_03", name: "Pull Shot Against Short Throw", duration: "12 mins",
        description: "Partner throws short-pitched balls — play the pull shot to the leg side. Builds the confidence to attack short bowling.",
        category: "Technical", football_benefit: "Scores runs off short-pitched deliveries under pressure",
        instructions: ["Batter takes guard, partner throws short from 6m", "Watch ball early — rock back, pull to leg side", "Keep head still — eye on the ball throughout", "20 pulls — count clean contacts"],
        success_feels_like: "You pick the length early and are already rocking back as the ball pitches.",
        gemini_scores: ["Early pick-up of length", "Head stillness", "Contact point above waist"],
        equipment_tier: "basic", position_tags: ["batsman"], muscles_targeted: ["forearms", "shoulders", "core"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
  bowler: {
    title: "Bowler Track",
    focus: "Run-up alignment, seam position, and accuracy.",
    drills: [
      {
        id: "cri_bo_01", name: "Run-Up Alignment Drill", duration: "15 mins",
        description: "Bowl 20 balls focusing on the same run-up line every delivery. Consistency in run-up creates consistency in line and length.",
        category: "Technical", football_benefit: "Repeatable action that bowls to a plan every ball",
        instructions: ["Mark your run-up with chalk or stones", "Bowl 20 deliveries — video your feet if possible", "Check: same side of crease, same gather step", "Flag any deliveries where run-up felt different"],
        success_feels_like: "Every delivery starts from exactly the same position on the crease.",
        gemini_scores: ["Run-up consistency", "Side-on position at crease", "Gather step timing"],
        equipment_tier: "basic", position_tags: ["bowler"], muscles_targeted: ["hip flexors", "shoulders", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "cri_bo_02", name: "Seam-Up Delivery Practice", duration: "12 mins",
        description: "Grip and release the ball with seam vertical on every delivery. Movement off the pitch depends on seam position.",
        category: "Technical", football_benefit: "Seam movement that beats batsmen without pace",
        instructions: ["Grip ball with two fingers on top, thumb below", "Check seam is perfectly vertical before each run-up", "Bowl at a single stump — aim for off-stump line", "20 bowls — count seam-up deliveries (check pitch mark)"],
        success_feels_like: "The ball pitches and moves — not skids through flat.",
        gemini_scores: ["Seam position at release", "Finger pressure on seam", "Wrist behind the ball"],
        equipment_tier: "basic", position_tags: ["bowler"], muscles_targeted: ["fingers", "wrists", "shoulders"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "cri_bo_03", name: "Off-Stump Target Bowling", duration: "15 mins",
        description: "Bowl at a coin placed on off-stump line, good length. The most dangerous line in cricket — builds disciplined line and length.",
        category: "Tactical", football_benefit: "Consistent off-stump line that generates wicket opportunities",
        instructions: ["Place a stone or coin on off-stump line, good length", "Bowl 20 balls — aim to hit or land beside the marker", "Count how many land within 30cm of marker", "Target: 14 out of 20"],
        success_feels_like: "The batsman plays at every ball — but cannot drive safely.",
        gemini_scores: ["Landing accuracy", "Length consistency", "Release point height"],
        equipment_tier: "basic", position_tags: ["bowler"], muscles_targeted: ["shoulders", "core", "hip flexors"],
        difficulty_level: 3, is_premium: false,
      },
    ],
  },
  allrounder: {
    title: "All-Rounder Track",
    focus: "Bat-ball transitions, fitness, and adaptability.",
    drills: [
      {
        id: "cri_ar_01", name: "Bat-Bowl Interval", duration: "20 mins",
        description: "5 minutes batting, then immediately bowl 6 balls, repeat. Simulates the physical and mental demands of playing both roles.",
        category: "Physical", football_benefit: "Manages energy across both disciplines in a long match day",
        instructions: ["5 min batting shadow against partner throws", "Immediately bowl 1 over at full effort", "Rest 60s — repeat 3 cycles", "Assess: does your batting or bowling quality drop in later cycles?"],
        success_feels_like: "Your bowling velocity at cycle 3 is the same as cycle 1.",
        gemini_scores: ["Batting quality in late cycles", "Bowling pace across cycles", "Recovery speed"],
        equipment_tier: "basic", position_tags: ["allrounder"], muscles_targeted: ["shoulders", "core", "quads"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "cri_ar_02", name: "Slip Catching Drill", duration: "12 mins",
        description: "Partner throws at varying heights and angles from 4m away — catch as a slip fielder. Quick hands are a key all-rounder weapon.",
        category: "Technical", football_benefit: "Catches chances in the slip cordon when bowling partnership is on",
        instructions: ["Stand in slip position — hands low and soft", "Partner throws at different heights without warning", "Catch with two hands — left, right, and both sides", "20 catches each — focus on soft hands"],
        success_feels_like: "The ball sticks — your hands absorb the ball rather than grabbing.",
        gemini_scores: ["Reaction time", "Hands softness", "Dive range to side"],
        equipment_tier: "basic", position_tags: ["allrounder"], muscles_targeted: ["forearms", "shoulders", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "cri_ar_03", name: "Variation Delivery Practice", duration: "15 mins",
        description: "Bowl: outswinger, inswinger, slower ball — three deliveries in a row, same run-up. Batsmen cannot read the variation.",
        category: "Tactical", football_benefit: "Variety that keeps batsmen guessing across an entire spell",
        instructions: ["Bowl 3-ball mini-overs: out / in / slower", "Same body action for all three deliveries", "Partner calls which delivery they think is coming", "Target: partner wrong more than half the time"],
        success_feels_like: "All three deliveries leave your hand looking identical.",
        gemini_scores: ["Action disguise", "Release point consistency", "Variation effectiveness"],
        equipment_tier: "basic", position_tags: ["allrounder"], muscles_targeted: ["wrists", "fingers", "shoulders"],
        difficulty_level: 3, is_premium: false,
      },
    ],
  },
};

// ─── SWIMMING ─────────────────────────────────────────────────────────────────

const SWIMMING: Record<string, PositionTrack> = {
  sprint: {
    title: "Sprint Track",
    focus: "Start, underwater phase, and explosive stroke cycle.",
    drills: [
      {
        id: "swm_sp_01", name: "Turn Acceleration Drill", duration: "15 mins",
        description: "Focus only on the last 5m into the wall and first 10m out. Turns win races — this drill trains the fastest part of the race.",
        category: "Technical", football_benefit: "Gains half a body length per turn on competitors",
        instructions: ["Start 5m from wall — dolphin kick in", "Touch — backflip turn — push hard off wall", "Maximum underwater dolphins (4–6)", "Accelerate to 10m mark at race pace"],
        success_feels_like: "You're faster off the wall than into it.",
        gemini_scores: ["Turn execution speed", "Underwater streamline", "Breakout timing"],
        equipment_tier: "zero", position_tags: ["sprint"], muscles_targeted: ["quads", "core", "calves"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "swm_sp_02", name: "Underwater Dolphin Kick", duration: "12 mins",
        description: "Push off the wall and dolphin kick to the flags (flags are usually 5m) without surfacing. Underwater speed is faster than surface speed.",
        category: "Physical", football_benefit: "Maximises the fastest phase of every length",
        instructions: ["Push hard off wall — arms in streamline overhead", "Dolphin kick: whole body wave — hips to toes", "Count kicks — aim for 6–8 to reach flags", "Repeat 8 times with full recovery"],
        success_feels_like: "You feel yourself shooting forward — not bobbing up and down.",
        gemini_scores: ["Kick amplitude", "Streamline tightness", "Distance per kick"],
        equipment_tier: "zero", position_tags: ["sprint"], muscles_targeted: ["core", "glutes", "calves"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "swm_sp_03", name: "Single-Arm Freestyle", duration: "10 mins",
        description: "Swim freestyle using one arm at a time. Isolates each arm's catch-pull-push cycle and fixes imbalances.",
        category: "Technical", football_benefit: "Builds equal power and correct mechanics on both sides",
        instructions: ["One arm extended forward — use only the other arm to pull", "Focus: high elbow catch, pull past hip, push through", "25m each arm — rest 30s", "Repeat 4 times each arm"],
        success_feels_like: "You feel the water catch early — like grabbing a fixed point.",
        gemini_scores: ["Catch depth", "Pull path straight back", "Elbow position"],
        equipment_tier: "zero", position_tags: ["sprint"], muscles_targeted: ["lats", "shoulders", "triceps"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
  endurance: {
    title: "Endurance Track",
    focus: "Pacing, bilateral breathing, and sustained output.",
    drills: [
      {
        id: "swm_en_01", name: "Descending Pace Set", duration: "20 mins",
        description: "Swim 4 × 100m — each one faster than the last. Builds the ability to pace and then find more speed when fatigued.",
        category: "Physical", football_benefit: "Negative split racing that saves the best for last",
        instructions: ["Swim 100m at 70% effort", "100m at 80% — faster than the first", "100m at 90% — faster again", "100m at 100% — best time of the set"],
        success_feels_like: "The last 100m is the fastest — you found energy in fatigue.",
        gemini_scores: ["Pace consistency within each 100m", "Split-to-split improvement", "Technique maintenance when tired"],
        equipment_tier: "zero", position_tags: ["endurance"], muscles_targeted: ["lats", "core", "legs"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "swm_en_02", name: "Bilateral Breathing Drill", duration: "12 mins",
        description: "Breathe every 3 strokes (alternating sides). Forces efficient oxygen use and builds a symmetrical stroke.",
        category: "Technical", football_benefit: "Balanced stroke and lower oxygen dependency",
        instructions: ["Swim at easy pace — breathe only every 3 strokes", "Alternate: right side / left side breathing", "If breathless, switch to 2-stroke breathing until recovered", "Build to 400m continuous bilateral breathing"],
        success_feels_like: "You are relaxed and in control — not starved of air.",
        gemini_scores: ["Breathing timing", "Body rotation symmetry", "Head position on breath"],
        equipment_tier: "zero", position_tags: ["endurance"], muscles_targeted: ["lats", "core", "shoulders"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "swm_en_03", name: "Kick Board Endurance", duration: "15 mins",
        description: "Hold a kick board and kick 8 × 25m using only your legs. Isolates leg strength and kick efficiency.",
        category: "Physical", football_benefit: "Strong kick that sustains body position in the final metres",
        instructions: ["Hold kick board with arms extended", "Kick 25m as fast as possible", "Rest 20s at the wall", "Repeat 8 times — count kicks per length to check efficiency"],
        success_feels_like: "Your hips stay at the surface — not sinking with each kick.",
        gemini_scores: ["Kick origin (hips vs knees)", "Kick amplitude", "Body position"],
        equipment_tier: "basic", position_tags: ["endurance"], muscles_targeted: ["quads", "hip flexors", "core"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
  stroke: {
    title: "Stroke Technique Track",
    focus: "Butterfly, backstroke, and breaststroke mechanics.",
    drills: [
      {
        id: "swm_st_01", name: "Butterfly Two-Kick Timing", duration: "12 mins",
        description: "Swim butterfly focusing on two distinct kicks per stroke cycle. The second kick propels the recovery — most swimmers miss it.",
        category: "Technical", football_benefit: "Correct butterfly timing that maintains rhythm without exhaustion",
        instructions: ["Swim half butterfly at reduced speed", "Count: kick on entry, kick on pull", "Make second kick sharp and deliberate", "10 × 25m focusing only on timing"],
        success_feels_like: "Both kicks feel equally sharp — and you glide between them.",
        gemini_scores: ["Two-kick timing", "Undulation rhythm", "Arm entry width"],
        equipment_tier: "zero", position_tags: ["stroke"], muscles_targeted: ["core", "glutes", "shoulders"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "swm_st_02", name: "Backstroke Rotation Pull", duration: "12 mins",
        description: "Exaggerate shoulder roll on each stroke. Proper body rotation is the engine of backstroke — not just arm pulling.",
        category: "Technical", football_benefit: "Generates power through rotation rather than arm effort alone",
        instructions: ["Swim backstroke at easy pace", "Exaggerate shoulder roll — ear almost touches water", "Each arm entry pulls from a fully rotated position", "8 × 25m focusing on rotation amplitude"],
        success_feels_like: "Your body rolls as a unit — and each pull starts from your hips.",
        gemini_scores: ["Rotation angle", "Arm entry at shoulder line", "Kick consistency"],
        equipment_tier: "zero", position_tags: ["stroke"], muscles_targeted: ["lats", "obliques", "shoulders"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "swm_st_03", name: "Breaststroke Pullout", duration: "10 mins",
        description: "Push off wall — complete one perfect pullout before surfacing. The breaststroke pullout is the fastest point in the race.",
        category: "Technical", football_benefit: "Maximises breaststroke turn advantage with a legal pullout",
        instructions: ["Push hard off wall in tight streamline", "One large arm pull — glide hands to thighs", "One kick — glide until speed equals surface speed", "Surface and continue — repeat 10 times from each wall"],
        success_feels_like: "You surface with speed — not slowing down when you come up.",
        gemini_scores: ["Streamline tightness", "Pullout timing", "Surface speed vs underwater speed"],
        equipment_tier: "zero", position_tags: ["stroke"], muscles_targeted: ["lats", "core", "quads"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
};

// ─── TENNIS ──────────────────────────────────────────────────────────────────

const TENNIS: Record<string, PositionTrack> = {
  baseline: {
    title: "Baseline Player Track",
    focus: "Groundstroke consistency, depth, and crosscourt control.",
    drills: [
      {
        id: "ten_bl_01", name: "Crosscourt Groundstroke Rally", duration: "15 mins",
        description: "Rally crosscourt only with a partner — forehand to forehand, then backhand to backhand. Builds depth and consistency under repetition.",
        category: "Technical", football_benefit: "Consistent crosscourt rally ball that opens the court",
        instructions: ["Both players rally forehand crosscourt for 5 mins", "Count your longest rally without error", "Switch to backhand crosscourt for 5 mins", "Aim: 15+ consecutive crosscourt shots"],
        success_feels_like: "You hit every ball with the same swing — no big misses.",
        gemini_scores: ["Ball depth", "Swing consistency", "Recovery position after each shot"],
        equipment_tier: "basic", position_tags: ["baseline"], muscles_targeted: ["forearms", "shoulders", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "ten_bl_02", name: "Inside-Out Forehand", duration: "12 mins",
        description: "Stand on the backhand side — run around to hit your forehand inside-out to the opponent's backhand corner. The weapon that dominates from the baseline.",
        category: "Technical", football_benefit: "Attacks the opponent's weaker backhand wing repeatedly",
        instructions: ["Coach feeds to your backhand side", "Run around — hit forehand inside-out to far corner", "Recover fast to centre — next ball coming quickly", "15 repetitions at match pace"],
        success_feels_like: "You hit the inside-out forehand from outside the court into the open corner.",
        gemini_scores: ["Ball direction to corner", "Recovery speed", "Contact point in front of body"],
        equipment_tier: "basic", position_tags: ["baseline"], muscles_targeted: ["core", "shoulders", "quads"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "ten_bl_03", name: "Backhand Slice Approach", duration: "12 mins",
        description: "Hit a low slice to the opponent's feet and come to net. Builds the approach shot that forces a difficult passing shot.",
        category: "Tactical", football_benefit: "Short-ball approach that puts opponent on the defensive",
        instructions: ["Coach feeds short ball — approach at pace", "Hit low slice aimed at opponent's feet", "Follow the shot into the net position", "Volley the return — 15 repetitions"],
        success_feels_like: "Your slice stays low and the opponent has to dig the ball up.",
        gemini_scores: ["Slice angle", "Approach footwork", "Net position after shot"],
        equipment_tier: "basic", position_tags: ["baseline"], muscles_targeted: ["forearms", "shoulders", "quads"],
        difficulty_level: 3, is_premium: false,
      },
    ],
  },
  "serve-volley": {
    title: "Serve & Volley Track",
    focus: "Serve placement, approach, and volley finishing.",
    drills: [
      {
        id: "ten_sv_01", name: "Serve + 1 Approach", duration: "15 mins",
        description: "Serve wide, split-step as the return comes, and play the next ball. Builds the automatic serve-and-recover that serve-volleyers need.",
        category: "Tactical", football_benefit: "Forces a weak return that can be attacked at the net",
        instructions: ["Serve wide to deuce or ad court", "Sprint forward — split step as opponent contacts ball", "Play the next ball aggressively", "20 first serves + transitions each side"],
        success_feels_like: "You are at the service line before the return is hit.",
        gemini_scores: ["Serve placement width", "Sprint timing after serve", "Split-step timing"],
        equipment_tier: "basic", position_tags: ["serve-volley"], muscles_targeted: ["quads", "calves", "shoulders"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "ten_sv_02", name: "Low Volley Finish", duration: "12 mins",
        description: "Partner feeds low volleys at your feet — finish with a short angled shot. The hardest volley in tennis to execute cleanly.",
        category: "Technical", football_benefit: "Wins the point from a difficult low ball at the net",
        instructions: ["Stand at net — partner feeds low balls at your feet", "Bend your knees — do not drop the racket head", "Short punch to a side angle", "20 reps — alternate left and right angles"],
        success_feels_like: "The low volley goes crosscourt at low height — not into the net.",
        gemini_scores: ["Knee bend", "Racket face angle", "Ball height over net"],
        equipment_tier: "basic", position_tags: ["serve-volley"], muscles_targeted: ["quads", "forearms", "core"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "ten_sv_03", name: "Overhead Smash", duration: "10 mins",
        description: "Practice the overhead from lob feeds. Finishing the point when the opponent lobs is the serve-volleyer's biggest weapon.",
        category: "Technical", football_benefit: "Finishes the point when opponent is forced to lob",
        instructions: ["Partner lobs from baseline", "Turn sideways, non-racket hand points to ball", "Throw racket head at ball from full extension", "Aim: far corner of service box — 15 smashes"],
        success_feels_like: "Contact point is at full extension above your head — not beside you.",
        gemini_scores: ["Contact point height", "Sideways position", "Target accuracy"],
        equipment_tier: "basic", position_tags: ["serve-volley"], muscles_targeted: ["shoulders", "triceps", "core"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
  "all-court": {
    title: "All-Court Track",
    focus: "Transitions, court coverage, and tactical flexibility.",
    drills: [
      {
        id: "ten_ac_01", name: "Approach Shot + Volley Combo", duration: "15 mins",
        description: "Coach feeds short — hit approach shot, come to net, play the volley. Practices the full sequence in one drill.",
        category: "Tactical", football_benefit: "Wins the net transition point in one smooth sequence",
        instructions: ["Coach feeds short ball to midcourt", "Hit approach shot down the line", "Sprint to net — split step — volley the crosscourt return", "15 repetitions — track your conversion rate"],
        success_feels_like: "The approach sets up an easy put-away volley every time.",
        gemini_scores: ["Approach placement", "Net sprint speed", "Volley decisiveness"],
        equipment_tier: "basic", position_tags: ["all-court"], muscles_targeted: ["quads", "forearms", "core"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "ten_ac_02", name: "Transition Footwork Drill", duration: "12 mins",
        description: "Cones placed at baseline, service line, and net — sprint between them on command. All-court tennis requires rapid court level changes.",
        category: "Physical", football_benefit: "Covers all three court positions in one continuous movement",
        instructions: ["Mark cones at: baseline, service line, net", "Coach calls: 'base!', 'mid!', 'net!' randomly", "Sprint to called cone — touch and hold split step", "2-min rounds, 60s rest, repeat 4 times"],
        success_feels_like: "You arrive at each position in balance — not falling forward.",
        gemini_scores: ["Reaction speed", "Balance on arrival", "Split-step timing"],
        equipment_tier: "zero", position_tags: ["all-court"], muscles_targeted: ["quads", "calves", "glutes"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "ten_ac_03", name: "Drop Shot Recovery", duration: "10 mins",
        description: "Partner hits a drop shot — sprint to reach it, lob or pass the player coming to net. Builds the ability to win from a defensive position.",
        category: "Tactical", football_benefit: "Turns a defensive position into an attacking counter",
        instructions: ["Start at baseline", "Partner hits drop shot without warning", "Sprint and reach the ball — try to lob over the net player", "Recover to baseline quickly — repeat 15 times"],
        success_feels_like: "You reach the ball and still find a good lob or angle.",
        gemini_scores: ["Sprint urgency", "Shot selection under pressure", "Recovery speed"],
        equipment_tier: "basic", position_tags: ["all-court"], muscles_targeted: ["quads", "calves", "shoulders"],
        difficulty_level: 3, is_premium: false,
      },
    ],
  },
};

// ─── VOLLEYBALL ───────────────────────────────────────────────────────────────

const VOLLEYBALL: Record<string, PositionTrack> = {
  setter: {
    title: "Setter Track",
    focus: "Setting accuracy, back-set, and decision-making under pressure.",
    drills: [
      {
        id: "vol_se_01", name: "Two-Ball Setting Drill", duration: "15 mins",
        description: "Partner throws two balls in quick succession — set each accurately to target. Builds hand speed and decision-making.",
        category: "Technical", football_benefit: "Quick, accurate sets even when balls arrive in awkward sequence",
        instructions: ["Stand at setter position — partner throws two balls 1s apart", "Set ball 1 to outside hitter, ball 2 to middle", "Alternate the set targets every 2 sets", "20 two-ball sequences"],
        success_feels_like: "Both sets reach the target without a second thought.",
        gemini_scores: ["Set height accuracy", "Foot position under ball", "Wrist snap consistency"],
        equipment_tier: "basic", position_tags: ["setter"], muscles_targeted: ["wrists", "forearms", "shoulders"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "vol_se_02", name: "Back-Set Accuracy", duration: "12 mins",
        description: "Set the ball behind you to the opposite side without looking. The back-set creates confusion — if it is inaccurate, the attack fails.",
        category: "Technical", football_benefit: "Unpredictable attack that splits the block",
        instructions: ["Stand at setting position", "Self-toss, then back-set behind you to marked zone", "Focus: hands open wide, push ball back from wrists", "20 back-sets — count accurate ones"],
        success_feels_like: "The back-set rises perfectly without spinning sideways.",
        gemini_scores: ["Set height", "Set direction accuracy", "Body position during set"],
        equipment_tier: "basic", position_tags: ["setter"], muscles_targeted: ["wrists", "fingers", "shoulders"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "vol_se_03", name: "Setting Under Pursuit", duration: "10 mins",
        description: "Pass is thrown wide — setter runs, platform passes, then sets. Simulates the realistic setting conditions in every game.",
        category: "Tactical", football_benefit: "Maintains setting quality from a compromised start position",
        instructions: ["Coach throws ball wide of the setting zone", "Setter runs, forearm passes ball up", "Immediately positions and sets to target", "15 wide throws from each side"],
        success_feels_like: "Even running full speed, your set still reaches the target at the right height.",
        gemini_scores: ["Platform pass accuracy", "Transition speed to set", "Set accuracy from off-position"],
        equipment_tier: "basic", position_tags: ["setter"], muscles_targeted: ["forearms", "quads", "core"],
        difficulty_level: 3, is_premium: false,
      },
    ],
  },
  spiker: {
    title: "Spiker Track",
    focus: "Approach timing, arm swing, and angle shooting.",
    drills: [
      {
        id: "vol_sp_01", name: "4-Step Approach Timing", duration: "15 mins",
        description: "Approach from 3m behind the net, time your jump to the set, and spike into a cone target. Timing is everything.",
        category: "Technical", football_benefit: "Generates maximum power by peaking at the exact contact point",
        instructions: ["Start 3m from net — 4-step approach: right-left-right-left (for right-handers)", "Swing arms back on third step, jump on fourth", "Contact ball at highest point — spike to target cone", "15 repetitions — track cone hits"],
        success_feels_like: "You contact the ball at the peak of your jump — not on the way down.",
        gemini_scores: ["Approach timing", "Jump height", "Arm swing speed at contact"],
        equipment_tier: "basic", position_tags: ["spiker"], muscles_targeted: ["quads", "shoulders", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "vol_sp_02", name: "Off-Speed Tip Placement", duration: "10 mins",
        description: "On a set, fake the hard spike then tip to an open area of the court. The most demoralising shot for a solid block.",
        category: "Tactical", football_benefit: "Wins points when the block is set for a hard spike",
        instructions: ["Full approach as for a hard spike", "At contact: extend one finger — soft tip to the seam", "Target: behind the blockers but in front of defence", "10 tips left side, 10 right side"],
        success_feels_like: "The ball drops inside the 3m line before the defence can move.",
        gemini_scores: ["Fake quality", "Tip placement accuracy", "Landing position behind block"],
        equipment_tier: "basic", position_tags: ["spiker"], muscles_targeted: ["shoulders", "fingers", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "vol_sp_03", name: "Angle Cut Shot", duration: "12 mins",
        description: "Hit a sharp angle spike that goes past the outside blocker and lands in the corner. The highest-percentage spike for outside hitters.",
        category: "Technical", football_benefit: "High-percentage scoring shot past a single outside block",
        instructions: ["Receive set at outside position", "Jump — contact ball slightly outside your body", "Swing arm across your body — aim far corner", "15 angle spikes — count balls that stay in court"],
        success_feels_like: "The ball drops at a steep angle in the far sideline corner.",
        gemini_scores: ["Contact point relative to body", "Arm angle at swing", "Ball landing position"],
        equipment_tier: "basic", position_tags: ["spiker"], muscles_targeted: ["shoulders", "core", "quads"],
        difficulty_level: 3, is_premium: false,
      },
    ],
  },
  libero: {
    title: "Libero Track",
    focus: "Dig positioning, serve receive, and emergency passes.",
    drills: [
      {
        id: "vol_li_01", name: "Dig Positioning Triangle", duration: "15 mins",
        description: "Three positions in backcourt — move between them as coach points. Drills the read-and-react positioning that makes a world-class libero.",
        category: "Tactical", football_benefit: "Always positioned before the ball arrives — not reacting after",
        instructions: ["Mark 3 positions in backcourt triangle", "Coach points to a position — sprint and set dig platform", "Coach throws ball to that position immediately", "Dig back to setter — 20 repetitions"],
        success_feels_like: "You arrive in position before the ball is thrown.",
        gemini_scores: ["Positioning speed", "Platform readiness on arrival", "Dig accuracy back to setter"],
        equipment_tier: "basic", position_tags: ["libero"], muscles_targeted: ["quads", "glutes", "forearms"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "vol_li_02", name: "Serve Receive Platform", duration: "12 mins",
        description: "Partner serves from the net — libero passes to a target zone. Consistent serve receive sets the setter up for an easy attack.",
        category: "Technical", football_benefit: "Controlled serve receive that puts the setter in rhythm",
        instructions: ["Partner serves 20 balls from various court positions", "Platform pass every receive to the 3m line target zone", "Arms must be flat and angled before the ball arrives", "Count passes that land in target zone"],
        success_feels_like: "Every pass rises and hangs — the setter barely has to move.",
        gemini_scores: ["Platform angle", "Pass height", "Target accuracy"],
        equipment_tier: "basic", position_tags: ["libero"], muscles_targeted: ["forearms", "quads", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "vol_li_03", name: "Dive and Roll Recovery", duration: "10 mins",
        description: "Ball thrown wide or short — dive to make the dig, roll, and recover to feet quickly. The libero's emergency dig that saves points.",
        category: "Physical", football_benefit: "Saves balls that look unreachable — often changes the match",
        instructions: ["Start at centre backcourt", "Coach throws wide or short unexpectedly", "Dive — make platform contact — roll smoothly", "Recover to feet in under 2 seconds — repeat 15 times"],
        success_feels_like: "You are back on your feet before the ball reaches the setter.",
        gemini_scores: ["Contact quality on dive", "Roll smoothness", "Recovery speed to feet"],
        equipment_tier: "zero", position_tags: ["libero"], muscles_targeted: ["core", "forearms", "quads"],
        difficulty_level: 3, is_premium: false,
      },
    ],
  },
};

// ─── HOCKEY ──────────────────────────────────────────────────────────────────

const HOCKEY: Record<string, PositionTrack> = {
  forward: {
    title: "Forward Track",
    focus: "First touch into space, circle entry, and finishing.",
    drills: [
      {
        id: "hoc_fw_01", name: "First Touch into Space", duration: "12 mins",
        description: "Receive a pass and redirect your first touch into space at pace. A poor first touch costs a scoring chance — a great one creates one.",
        category: "Technical", football_benefit: "Creates a scoring chance from a routine pass with one touch",
        instructions: ["Partner passes from 10m at match pace", "First touch directs ball into marked space zone", "Follow the ball into the zone at full speed", "Alternate: touch left / touch right — 20 reps each side"],
        success_feels_like: "The ball never stops — it redirects and you chase it at full pace.",
        gemini_scores: ["Touch direction", "Touch distance into space", "Acceleration onto first touch"],
        equipment_tier: "basic", position_tags: ["forward"], muscles_targeted: ["forearms", "wrists", "quads"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "hoc_fw_02", name: "Drag Flick at Goal", duration: "15 mins",
        description: "Drag the ball across your body and flick at goal in one flowing movement. The most dangerous short-corner skill in modern hockey.",
        category: "Technical", football_benefit: "Scores directly from penalty corners with a powerful low shot",
        instructions: ["Ball stationary 2m from goal line", "Low body position — drag ball left to right", "Accelerate stick through, flick low at corner of goal", "Aim: bottom corners — 20 flicks"],
        success_feels_like: "The flick stays low and arrives before the goalkeeper can move.",
        gemini_scores: ["Drag path", "Flick velocity", "Target accuracy (bottom corners)"],
        equipment_tier: "basic", position_tags: ["forward"], muscles_targeted: ["wrists", "forearms", "core"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "hoc_fw_03", name: "Circle Entry Sprint", duration: "10 mins",
        description: "Sprint from midfield, beat a cone defender, and get your shot off in the circle. Gets forwards comfortable with the burst required to enter and shoot.",
        category: "Physical", football_benefit: "Creates a clean shooting chance inside the circle at pace",
        instructions: ["Start at halfway, sprint toward cone defender at circle edge", "Beat the cone left or right", "Shoot immediately on entry into circle", "Repeat 12 times — alternate sides"],
        success_feels_like: "You shoot before your body slows down from the sprint.",
        gemini_scores: ["Sprint to cone speed", "Beat direction decisiveness", "Shot timing on entry"],
        equipment_tier: "basic", position_tags: ["forward"], muscles_targeted: ["quads", "hamstrings", "forearms"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
  midfielder: {
    title: "Midfielder Track",
    focus: "Switching play, winning turnovers, and press triggers.",
    drills: [
      {
        id: "hoc_mi_01", name: "Reverse Stick Pass", duration: "12 mins",
        description: "Play accurate short passes using the reverse stick. Midfielders must be comfortable on both sides to keep possession.",
        category: "Technical", football_benefit: "Keeps ball in tight areas without turning and losing possession",
        instructions: ["Partner stands 5m to your left", "Receive ball on the right, play reverse stick pass to partner", "Focus: stick face opens cleanly, push along the ground", "20 reverse passes — count accurate ones"],
        success_feels_like: "The reverse stick pass arrives on your partner's stick cleanly — not bouncing.",
        gemini_scores: ["Stick face angle", "Pass weight", "Body position before pass"],
        equipment_tier: "basic", position_tags: ["midfielder"], muscles_targeted: ["wrists", "forearms", "core"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "hoc_mi_02", name: "Press Trigger & Win", duration: "15 mins",
        description: "Identify when the opponent's touch is heavy — trigger the press and win the ball. Turnovers in midfield are the most valuable moments in hockey.",
        category: "Tactical", football_benefit: "Wins possession in dangerous midfield areas through intelligent pressing",
        instructions: ["Coach rolls ball to target player with varying touch quality", "Defender watches: light touch = stay back, heavy touch = press", "Sprint on heavy touch — reach ball before target controls", "15 repetitions — call before pressing"],
        success_feels_like: "You win the ball before the opponent raises their head.",
        gemini_scores: ["Press decision accuracy", "Sprint on trigger", "Ball-winning technique"],
        equipment_tier: "basic", position_tags: ["midfielder"], muscles_targeted: ["quads", "calves", "core"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "hoc_mi_03", name: "Wide Switch Pass", duration: "12 mins",
        description: "Receive the ball centrally and switch play with one long pass to the opposite wing. Changes the point of attack and stretches the defence.",
        category: "Tactical", football_benefit: "Moves defence laterally to create space on the far side",
        instructions: ["Receive pass centrally from behind", "Immediately look right — long pass to right wing cone", "Then receive centrally — switch left", "20 switches each side — count accurate arrivals"],
        success_feels_like: "The ball arrives flat and on the stick of the winger without breaking stride.",
        gemini_scores: ["Pass accuracy to far wing", "Switch decision speed", "Ball weight (not too hard, not too soft)"],
        equipment_tier: "basic", position_tags: ["midfielder"], muscles_targeted: ["shoulders", "core", "forearms"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
  defender: {
    title: "Defender Track",
    focus: "Stick tackle, clearance, and compact shape.",
    drills: [
      {
        id: "hoc_df_01", name: "Jab Tackle Timing", duration: "12 mins",
        description: "Wait for the attacker to overrun the ball — jab the stick in to dispossess. The disciplined defender wins more tackles than the lunging one.",
        category: "Technical", football_benefit: "Dispossesses attackers without committing to a lunge",
        instructions: ["Attacker dribbles toward you from 10m", "Hold your shape — do not lunge early", "Jab stick toward ball when attacker's touch goes long", "10 reps — count clean tackles vs cards for lunging"],
        success_feels_like: "You wait until the moment is right — then the ball is yours.",
        gemini_scores: ["Tackle timing", "Body positioning before tackle", "Recovery if missed"],
        equipment_tier: "basic", position_tags: ["defender"], muscles_targeted: ["forearms", "quads", "core"],
        difficulty_level: 3, is_premium: false,
      },
      {
        id: "hoc_df_02", name: "Clearance Under Pressure", duration: "12 mins",
        description: "Ball arrives in the circle under pressure — clear it strongly out of danger. Every defender must clear confidently under challenge.",
        category: "Technical", football_benefit: "Relieves pressure by winning the ball and clearing danger",
        instructions: ["Ball played into circle from wide position", "Defender moves to intercept with confidence", "Strong slap clearance to sideline — not back through centre", "15 clearances — count successful ones to sideline"],
        success_feels_like: "The clearance reaches the sideline and removes all danger.",
        gemini_scores: ["Interception decision", "Clearance direction (not through middle)", "Contact power"],
        equipment_tier: "basic", position_tags: ["defender"], muscles_targeted: ["forearms", "core", "quads"],
        difficulty_level: 2, is_premium: false,
      },
      {
        id: "hoc_df_03", name: "Compact Shape Drill", duration: "10 mins",
        description: "Three defenders slide left and right together on coach command — maintaining compact shape that blocks through-passes.",
        category: "Tactical", football_benefit: "Denies space between defenders for attackers to penetrate",
        instructions: ["3 defenders stand in a line 2m apart", "Coach calls 'left' or 'right' — all slide together", "Maintain 2m gap — no player falls behind the others", "2-minute rounds — coach speeds up calls over time"],
        success_feels_like: "The line moves as one unit — no gaps open up at any point.",
        gemini_scores: ["Slide synchronisation", "Gap maintenance", "Communication speed"],
        equipment_tier: "zero", position_tags: ["defender"], muscles_targeted: ["quads", "glutes", "calves"],
        difficulty_level: 2, is_premium: false,
      },
    ],
  },
};

// ─── Combined export ─────────────────────────────────────────────────────────

export const SPORT_DRILLS: Record<string, Record<string, PositionTrack>> = {
  rugby:      RUGBY,
  athletics:  ATHLETICS,
  netball:    NETBALL,
  basketball: BASKETBALL,
  cricket:    CRICKET,
  swimming:   SWIMMING,
  tennis:     TENNIS,
  volleyball: VOLLEYBALL,
  hockey:     HOCKEY,
};

/**
 * Returns the drill set for a given sport.
 * Returns an empty object for football — the caller should fall back to FOOTBALL_POSITION_DRILLS.
 */
export function getSportDrills(sport: string): Record<string, PositionTrack> {
  return SPORT_DRILLS[sport] ?? {};
}

export type { DrillData };
