// THUTO Conditioning — 15 curated seed cards (offline fallback)
// These work without the backend. API cards override these when available.

import type { ExerciseCard } from "./types";

export const SEED_CARDS: ExerciseCard[] = [
  // ─── FIFA 11+ Warmup ───────────────────────────────────────────────────────
  {
    id: "seed-001",
    name: "Running Straight Ahead",
    category: "fifa_warmup",
    equipment_tier: "zero",
    difficulty_level: 1,
    duration_seconds: 60,
    reps: null,
    instructions: [
      "Jog across the pitch at medium pace",
      "Keep chest up and arms relaxed",
      "Land on mid-foot, not heel",
    ],
    muscles_targeted: ["quadriceps", "hamstrings", "calves"],
    football_benefit: "Prepares legs for match speed and reduces hamstring injury risk",
    phase_of_play: "general",
    position_tags: ["goalkeeper", "winger", "midfielder", "defender", "striker", "fullback"],
    age_min: 13,
    age_max: 40,
    thuto_question: "How do your legs feel — any tightness in the back of your thigh?",
    success_feels_like: "Light feet, breathing easy, muscles warm",
    is_fifa_11plus: true,
    is_active: true,
  },
  {
    id: "seed-002",
    name: "Hip Cross-Over",
    category: "fifa_warmup",
    equipment_tier: "zero",
    difficulty_level: 1,
    duration_seconds: 45,
    reps: "10 each leg",
    instructions: [
      "Stand on one leg, swing the other leg across your body",
      "Keep your balance — arms out for stability",
      "Open the leg wide on the return swing",
      "Switch legs after 10 reps",
    ],
    muscles_targeted: ["hip flexors", "glutes", "adductors"],
    football_benefit: "Opens hips for kicking, turning, and sliding tackles",
    phase_of_play: "general",
    position_tags: ["goalkeeper", "winger", "midfielder", "defender", "striker", "fullback"],
    age_min: 13,
    age_max: 40,
    thuto_question: "Can you hold your balance on one leg for a full swing? That balance is what protects your ankle when you land from a header.",
    success_feels_like: "Hips feel loose and warm, balance feels natural",
    is_fifa_11plus: true,
    is_active: true,
  },
  {
    id: "seed-003",
    name: "Shoulder Contact",
    category: "fifa_warmup",
    equipment_tier: "zero",
    difficulty_level: 1,
    duration_seconds: 60,
    reps: null,
    instructions: [
      "Walk in pairs side by side",
      "Every 3–4 steps, bump shoulders lightly with your partner",
      "Keep upright — do not lean into the contact",
      "Swap sides every 20 metres",
    ],
    muscles_targeted: ["core", "shoulder stabilisers"],
    football_benefit: "Trains body to absorb contact without losing balance — key for shielding the ball",
    phase_of_play: "in_possession",
    position_tags: ["striker", "midfielder", "defender", "fullback"],
    age_min: 13,
    age_max: 40,
    thuto_question: "Who is stronger in the shoulder — you or your partner? The one who stays upright wins the physical battle every time.",
    success_feels_like: "Stable, grounded, you are not moved by the contact",
    is_fifa_11plus: true,
    is_active: true,
  },

  // ─── Aerobic ───────────────────────────────────────────────────────────────
  {
    id: "seed-004",
    name: "4-Cone Aerobic Box",
    category: "aerobic",
    equipment_tier: "zero",
    difficulty_level: 2,
    duration_seconds: 480,
    reps: null,
    instructions: [
      "Set up 4 cones in a 15m × 15m square (or use shirt markers)",
      "Jog around the outside of the square continuously for 8 minutes",
      "Every lap: accelerate on one side, jog on the other three",
      "Target: heart rate feels like you could still hold a conversation",
    ],
    muscles_targeted: ["quadriceps", "calves", "heart"],
    football_benefit: "Builds the aerobic base that powers the last 20 minutes of a match",
    phase_of_play: "general",
    position_tags: ["midfielder", "winger", "fullback", "striker"],
    age_min: 13,
    age_max: 40,
    thuto_question: "By minute 6, how hard is your breathing? If you cannot speak a sentence, slow down — we are building your engine today, not breaking it.",
    success_feels_like: "Comfortable tiredness. Lungs working but not burning.",
    is_fifa_11plus: false,
    is_active: true,
  },
  {
    id: "seed-005",
    name: "Fartlek Run",
    category: "aerobic",
    equipment_tier: "zero",
    difficulty_level: 2,
    duration_seconds: 600,
    reps: null,
    instructions: [
      "Start jogging at easy pace",
      "Every time you see a landmark (tree, cone, corner flag) — sprint to it",
      "Jog again until you pick the next landmark",
      "Mix the distances: sometimes 10m, sometimes 40m",
      "Total: 10 minutes",
    ],
    muscles_targeted: ["whole body", "heart", "calves", "quadriceps"],
    football_benefit: "Mimics the random sprint-recover pattern of a real football match",
    phase_of_play: "general",
    position_tags: ["winger", "midfielder", "fullback", "striker"],
    age_min: 13,
    age_max: 40,
    thuto_question: "Pick your next target BEFORE you finish the current sprint. That is the same mental skill as spotting the next pass before the ball arrives.",
    success_feels_like: "Breathing is controlled after each sprint recovery. You chose your moments.",
    is_fifa_11plus: false,
    is_active: true,
  },

  // ─── HIIT ─────────────────────────────────────────────────────────────────
  {
    id: "seed-006",
    name: "30-30 Sprint Intervals",
    category: "hiit",
    equipment_tier: "zero",
    difficulty_level: 3,
    duration_seconds: 360,
    reps: "6 rounds",
    instructions: [
      "Mark a 20m sprint line",
      "Sprint as fast as possible for 30 seconds",
      "Walk back and rest for 30 seconds",
      "Repeat 6 times",
      "Rest 2 minutes, then do a second set if you have energy",
    ],
    muscles_targeted: ["quadriceps", "hamstrings", "calves", "glutes"],
    football_benefit: "Builds explosive speed that wins the crucial 5m races against opponents",
    phase_of_play: "transition_attacking",
    position_tags: ["winger", "striker", "fullback"],
    age_min: 15,
    age_max: 35,
    thuto_question: "Are you running with your arms or just your legs? Your arms drive you forward — pump them hard like pistons.",
    success_feels_like: "Legs burning but you are still accelerating on round 5 and 6",
    is_fifa_11plus: false,
    is_active: true,
  },
  {
    id: "seed-007",
    name: "Pyramid Burpee",
    category: "hiit",
    equipment_tier: "zero",
    difficulty_level: 3,
    duration_seconds: 300,
    reps: "1-2-3-2-1 pyramid",
    instructions: [
      "Do 1 burpee, rest 5 seconds",
      "Do 2 burpees, rest 10 seconds",
      "Do 3 burpees, rest 15 seconds",
      "Do 2 burpees, rest 10 seconds",
      "Do 1 burpee — done",
      "Burpee: jump down, plank, press-up, jump up, clap above head",
    ],
    muscles_targeted: ["full body", "chest", "shoulders", "core", "legs"],
    football_benefit: "Builds the explosive power to win aerial duels and jump for headers",
    phase_of_play: "out_of_possession",
    position_tags: ["striker", "defender", "midfielder"],
    age_min: 14,
    age_max: 35,
    thuto_question: "Keep your hips low in the plank. A sagging hip means your core is not working — that same core protects your back in tackles.",
    success_feels_like: "Heart is pumping hard but technique stays clean on every rep",
    is_fifa_11plus: false,
    is_active: true,
  },

  // ─── Strength ─────────────────────────────────────────────────────────────
  {
    id: "seed-008",
    name: "Nordic Hamstring Curl",
    category: "strength",
    equipment_tier: "zero",
    difficulty_level: 3,
    duration_seconds: null,
    reps: "3 × 5",
    instructions: [
      "Kneel on soft ground. A partner holds your ankles or hook feet under a bench",
      "Slowly lower your body forward — resist with your hamstrings",
      "Go as far as you can with control, then catch yourself with hands",
      "Use hands to push back to start",
      "The goal: resist longer each session",
    ],
    muscles_targeted: ["hamstrings"],
    football_benefit: "The single most effective exercise for preventing hamstring tears — the most common football injury",
    phase_of_play: "general",
    position_tags: ["winger", "striker", "midfielder", "defender", "fullback", "goalkeeper"],
    age_min: 15,
    age_max: 40,
    thuto_question: "How far did you get before your hamstrings gave out? Even 5cm of resistance is building protection. Start slow, progress weekly.",
    success_feels_like: "Deep burn in the back of the thigh during the lowering. Not pain — burn.",
    is_fifa_11plus: true,
    is_active: true,
  },
  {
    id: "seed-009",
    name: "Single-Leg Squat",
    category: "strength",
    equipment_tier: "zero",
    difficulty_level: 2,
    duration_seconds: null,
    reps: "3 × 8 each leg",
    instructions: [
      "Stand on one leg. The other leg floats in front",
      "Slowly lower your body on the standing leg until knee is at 90°",
      "Keep knee over your second toe — do not let it collapse inward",
      "Push back up without wobbling",
      "Use a wall for balance if needed at first",
    ],
    muscles_targeted: ["quadriceps", "glutes", "ankle stabilisers"],
    football_benefit: "Builds the unilateral leg strength used in every kick, plant foot, and sprint push-off",
    phase_of_play: "general",
    position_tags: ["striker", "winger", "defender", "fullback", "midfielder"],
    age_min: 14,
    age_max: 40,
    thuto_question: "Watch your knee in the reflection or have a partner check. Is it tracking over your toe? Collapsed knee = knee injury waiting to happen.",
    success_feels_like: "Glute and quad both burning equally. Stable on landing.",
    is_fifa_11plus: false,
    is_active: true,
  },

  // ─── Agility ──────────────────────────────────────────────────────────────
  {
    id: "seed-010",
    name: "T-Drill",
    category: "agility",
    equipment_tier: "zero",
    difficulty_level: 2,
    duration_seconds: null,
    reps: "5 × each direction",
    instructions: [
      "Place 4 cones (or stones) in a T shape: bottom 9m from centre, arms 4.5m left and right",
      "Sprint from bottom to centre cone",
      "Sidestep LEFT to left cone (face forward the whole time)",
      "Sidestep RIGHT all the way to right cone",
      "Sidestep back to centre cone, then sprint back to start",
      "Rest 60 seconds between reps",
    ],
    muscles_targeted: ["quadriceps", "adductors", "abductors", "calves"],
    football_benefit: "Trains the lateral quickness needed to close down opponents and beat defenders 1v1",
    phase_of_play: "out_of_possession",
    position_tags: ["midfielder", "defender", "fullback", "winger"],
    age_min: 13,
    age_max: 35,
    thuto_question: "Are you crossing your feet on the sidestep? Keep feet parallel — crossing kills your speed and balance on the change of direction.",
    success_feels_like: "Sharp, crisp cuts. Each direction change feels explosive not stumbled.",
    is_fifa_11plus: false,
    is_active: true,
  },
  {
    id: "seed-011",
    name: "Reaction Shadowing",
    category: "agility",
    equipment_tier: "zero",
    difficulty_level: 2,
    duration_seconds: 120,
    reps: "2 × 1 minute",
    instructions: [
      "Stand 2 metres facing a partner",
      "Partner moves: forward, backward, left, right at random",
      "You mirror every movement — try to match them exactly",
      "Stay on the balls of your feet in a low athletic stance",
      "Switch roles after 1 minute",
    ],
    muscles_targeted: ["calves", "quadriceps", "core"],
    football_benefit: "Trains reaction time and footwork — essential for defenders tracking attackers",
    phase_of_play: "out_of_possession",
    position_tags: ["defender", "fullback", "goalkeeper", "midfielder"],
    age_min: 13,
    age_max: 40,
    thuto_question: "Are you watching your partner's hips or their feet? Hips never lie — they tell you where they are going before their feet move.",
    success_feels_like: "You are reacting before you think. Automatic.",
    is_fifa_11plus: false,
    is_active: true,
  },

  // ─── Plyometrics ──────────────────────────────────────────────────────────
  {
    id: "seed-012",
    name: "Broad Jump to Sprint",
    category: "plyometrics",
    equipment_tier: "zero",
    difficulty_level: 2,
    duration_seconds: null,
    reps: "6 reps",
    instructions: [
      "Stand with feet shoulder-width apart",
      "Bend knees, swing arms back, then jump as far forward as possible",
      "Land softly on both feet — absorb the landing with bent knees",
      "Immediately sprint hard for 10 metres after landing",
      "Walk back and repeat",
    ],
    muscles_targeted: ["glutes", "quadriceps", "calves", "hamstrings"],
    football_benefit: "Builds the explosive first-step acceleration that separates good players from great ones",
    phase_of_play: "transition_attacking",
    position_tags: ["striker", "winger", "midfielder"],
    age_min: 14,
    age_max: 35,
    thuto_question: "The jump and the sprint must be one movement. Do not pause after landing — your brain must learn to convert ground contact time into propulsion.",
    success_feels_like: "You feel like a spring releasing. The sprint feels effortless after the jump.",
    is_fifa_11plus: false,
    is_active: true,
  },
  {
    id: "seed-013",
    name: "Box Jump (Platform or Bench)",
    category: "plyometrics",
    equipment_tier: "basic",
    difficulty_level: 2,
    duration_seconds: null,
    reps: "4 × 6",
    instructions: [
      "Stand facing a sturdy bench or low platform (40–50 cm)",
      "Jump up onto the box with two feet — land softly",
      "Step down (do not jump down) and reset",
      "Focus: explode up, land quiet",
      "Rest 60 seconds between sets",
    ],
    muscles_targeted: ["glutes", "quadriceps", "calves"],
    football_benefit: "Develops the vertical power for winning headers and explosive jumping ability",
    phase_of_play: "out_of_possession",
    position_tags: ["striker", "defender", "goalkeeper"],
    age_min: 14,
    age_max: 35,
    thuto_question: "How loud is your landing? Aim for near-silent. A quiet landing means your muscles are absorbing force — not your joints.",
    success_feels_like: "Powerful take-off, soft landing. You could go again immediately.",
    is_fifa_11plus: false,
    is_active: true,
  },
  {
    id: "seed-014",
    name: "Depth Drop to Jump",
    category: "plyometrics",
    equipment_tier: "basic",
    difficulty_level: 3,
    duration_seconds: null,
    reps: "3 × 5",
    instructions: [
      "Stand on the edge of a low step or bench",
      "Step off (do not jump) — let gravity drop you",
      "The instant both feet touch ground, immediately jump as high as possible",
      "Minimal ground contact time — think of the ground as hot",
      "Rest 90 seconds between sets",
    ],
    muscles_targeted: ["glutes", "quadriceps", "calves", "Achilles tendon"],
    football_benefit: "Trains the stretch-shortening cycle — the elastic energy rebound that makes sprinting efficient",
    phase_of_play: "transition_attacking",
    position_tags: ["striker", "winger", "midfielder"],
    age_min: 16,
    age_max: 32,
    thuto_question: "Your tendons are springs. This exercise teaches your body to store and release elastic energy — the same mechanism that makes cheetahs fast.",
    success_feels_like: "Ground contact feels like a reflex — you barely touched the earth.",
    is_fifa_11plus: false,
    is_active: true,
  },
  {
    id: "seed-015",
    name: "Goalkeeper Lateral Bound",
    category: "plyometrics",
    equipment_tier: "zero",
    difficulty_level: 2,
    duration_seconds: null,
    reps: "3 × 8 each side",
    instructions: [
      "Stand on your right leg",
      "Bound sideways as far as possible off the right leg, land on left leg",
      "Hold the landing for 2 seconds — do not let the free foot touch down",
      "Bound back to the right",
      "Keep hips low — you are not hopping, you are diving",
    ],
    muscles_targeted: ["glutes", "adductors", "abductors", "single-leg stabilisers"],
    football_benefit: "Develops the explosive lateral dive needed for shot stopping — and the hip stability needed for injury prevention",
    phase_of_play: "out_of_possession",
    position_tags: ["goalkeeper", "defender", "fullback"],
    age_min: 14,
    age_max: 40,
    thuto_question: "Can you hold the landing for a full 2 seconds without wobbling? That stability is what keeps your ACL intact when you land from a save.",
    success_feels_like: "Each bound feels further. Landing feels planted — not wobbly.",
    is_fifa_11plus: false,
    is_active: true,
  },
];
