// app/api/world-cup/matches/route.ts
// Feeds the /worldcup page with live and completed World Cup matches from iSports API.
//
// ?status=live      → returns in-progress matches (score + minute + possession)
// ?status=completed → returns finished matches (score + tactical_report_generated flag)
// No status param   → returns all matches for today's date
export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

import { NextRequest, NextResponse } from 'next/server';
import { getLiveMatches, getMatchesByDate, getMatchesByLeague, type iSportsMatch } from '@/lib/isports/client';

const WORLD_CUP_LEAGUE_ID = '1';

function mapToPageMatch(m: iSportsMatch) {
  return {
    id:                        m.id,
    home_team:                 m.home_team?.name ?? 'TBD',
    away_team:                 m.away_team?.name ?? 'TBD',
    home_score:                m.home_score ?? 0,
    away_score:                m.away_score ?? 0,
    date:                      m.date ?? '',
    time:                      m.time ?? '',
    stadium:                   m.stadium ?? m.venue ?? 'TBD',
    city:                      m.city ?? 'TBD',
    minute:                    m.minute ?? m.time_elapsed ?? 0,
    // iSports match list doesn't include possession — default 50/50
    possession_home:           50,
    possession_away:           50,
    // tactical report is generated by the cron job after full-time
    tactical_report_generated: false,
  };
}

export async function GET(req: NextRequest) {
  const status = req.nextUrl.searchParams.get('status');

  try {
    if (status === 'live') {
      const raw = await getLiveMatches(WORLD_CUP_LEAGUE_ID);
      const live = raw.filter(m =>
        m.status === 'live' || m.status === 'first_half' || m.status === 'second_half'
      );
      return NextResponse.json({ matches: live.map(mapToPageMatch) });
    }

    if (status === 'completed') {
      // Fetch league matches and filter to finished ones
      const raw = await getMatchesByLeague(WORLD_CUP_LEAGUE_ID);
      const completed = raw.filter(m => m.status === 'finished');
      return NextResponse.json({ matches: completed.map(mapToPageMatch) });
    }

    // No status param — today's matches
    const today = new Date().toISOString().split('T')[0];
    const raw = await getMatchesByDate(today, WORLD_CUP_LEAGUE_ID);
    return NextResponse.json({ matches: raw.map(mapToPageMatch) });

  } catch (error) {
    console.error('iSports API error:', error);
    return NextResponse.json(
      { matches: [], error: error instanceof Error ? error.message : 'Failed to fetch matches' },
      { status: 500 }
    );
  }
}