import { NextResponse } from 'next/server';

export async function GET() {
  const modules = [
    {
      id: 'mod-0',
      matchId: 'match-0',
      title: 'Basics of Build-Up Play',
      subtitle: 'Zimbabwe vs Kenya - AFCON Qualifier 2026',
      homeTeam: 'Zimbabwe',
      awayTeam: 'Kenya',
      homeScore: 1,
      awayScore: 0,
      thumbnail: '',
      description: 'Learn the fundamentals of building out from the back.',
      tags: ['Build-Up', 'Passing', 'Beginner'],
      difficulty: 'beginner',
      duration: '20 min',
      lessonCount: 3,
      isLocked: false,
      isCompleted: false,
      progress: 0,
      createdAt: '2026-06-22T10:00:00Z',
    },
    {
      id: 'mod-3',
      matchId: 'match-3',
      title: 'Defensive Organization',
      subtitle: 'Morocco vs Spain - Round of 16 2026',
      homeTeam: 'Morocco',
      awayTeam: 'Spain',
      homeScore: 0,
      awayScore: 0,
      thumbnail: '',
      description: "Morocco's defensive masterclass against Spain's possession game.",
      tags: ['Defensive Shape', 'Low Block', 'Counter'],
      difficulty: 'intermediate',
      duration: '30 min',
      lessonCount: 3,
      isLocked: false,
      isCompleted: true,
      progress: 100,
      createdAt: '2026-06-15T10:00:00Z',
    },
    {
      id: 'mod-2',
      matchId: 'match-2',
      title: 'Pressing & Counter-Pressing',
      subtitle: 'Brazil vs Germany - Quarter-Final 2026',
      homeTeam: 'Brazil',
      awayTeam: 'Germany',
      homeScore: 2,
      awayScore: 1,
      thumbnail: '',
      description: "Learn how Brazil's high press overwhelmed Germany's build-up.",
      tags: ['Pressing', 'High Press', 'Build-up'],
      difficulty: 'intermediate',
      duration: '35 min',
      lessonCount: 4,
      isLocked: true,
      isCompleted: false,
      progress: 0,
      createdAt: '2026-06-18T10:00:00Z',
    },
    {
      id: 'mod-1',
      matchId: 'match-1',
      title: 'Transition Masterclass',
      subtitle: 'Argentina vs France - World Cup Final 2026',
      homeTeam: 'Argentina',
      awayTeam: 'France',
      homeScore: 3,
      awayScore: 2,
      thumbnail: '',
      description: "Study how Argentina exploited France's transitions to win the World Cup.",
      tags: ['Transition', 'Counter-Attack', 'Final'],
      difficulty: 'advanced',
      duration: '45 min',
      lessonCount: 5,
      isLocked: true,
      isCompleted: false,
      progress: 0,
      createdAt: '2026-06-20T10:00:00Z',
    },
  ];

  return NextResponse.json({ modules });
}
